/* Generated snapshot — see _rebuild_cabinet_data.js (recreate via Claude/MCP). */
window.NGE_DATA = {
  "version": 2,
  "generated": "2026-05-16T16:05:00.000Z",
  "generated_by": "Claude Opus 4.7 — Notion snapshot + parent data from signed contracts",
  "note": "PIN derived deterministically from student id. Teacher password SHA-256 hashed. Parent ФИО/passport/email/phone added from scanned contracts on 2026-05-16.",
  "teacher": {
    "id": "teacher",
    "name": "Мария Витальевна Бурцева",
    "passwordHash": "94d5d02aa86a4ad402c54025da0f758d9781db2de21c22c601c1903e7a8148ce"
  },
  "payment": {
    "tinkoffQuickPay": "https://www.tinkoff.ru/rm/r_PnDqHEqsDu.EkrmOLeXmQ/MIhLS10143",
    "telegram": "https://t.me/MariaBurceva_English",
    "phone": "89165101792",
    "recipient": "Бурцева Мария Витальевна",
    "contract": "5181572792",
    "account": "40817810200014652973",
    "bik": "044525974",
    "bank": "АО \"ТБанк\"",
    "correspondentAccount": "30101810145250000974",
    "inn": "7710140679",
    "kpp": "771301001",
    "purpose": "Перевод средств по договору № 5181572792 Бурцева Мария Витальевна НДС не облагается"
  },
  "students": [
    {
      "id": "andrei-kruglov",
      "notion_id": "34d7364c-ba79-81e0-9e00-eb54d63b0dc1",
      "name": "Андрей Круглов",
      "casual_greeting": true,
      "greeting_student": "Привет, Андрей",
      "greeting_parent": "Здравствуйте, Юлия Борисовна",
      "level": "B2",
      "format": "индивидуально",
      "duration": "1.5 часа",
      "lessons_per_week": 2,
      "schedule": "вторник 14:30 / четверг 10:30 (+20 мин)",
      "stability_note": "Актуализировано 20.05.2026: остаётся 3 урока до летних каникул — 27.05 (вт 14:30), 29.05 (чт 10:30+20мин), 02.06 (вт 14:30 — перенос чт-формата, время как обычное вт). После 02.06 уходит на каникулы до сентября 2026, с высылкой ему форм.",
      "goal": "разговорный английский, школа, подготовка к TOEFL/IELTS",
      "price_per_lesson": 2500,
      "monthly_package": 20000,
      "weekly_revenue": 5000,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contact_passport": "4520 965594",
      "contact_phone": "+79166988892",
      "contact_address": "Москва, ул. Ю. Парковая, 15-244",
      "pin": "1721",
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 8,
      "summer_plan_note": "Май-абонемент закрыт (8 из 8). Уходит на каникулы до сентября 2026 с серией заданий по уже пройденным темам. Летом — 3 контрольных встречи (конец июня / июля / августа) по обычному графику (вторник или четверг). Конспект года и летние задания доставляются лично от Маши (не публикуем).",
      "lessons": [
        { "date": "2026-05-06", "num": 1, "status": "completed", "topic": "Инструктажи — академическая лексика, структура задания, разбор формата" },
        { "date": "2026-05-08", "num": 2, "status": "completed", "topic": "Инструктажи — продолжение, отработка формата" },
        { "date": "2026-05-13", "num": 3, "status": "completed", "topic": "Разнообразие наук — решение типичных задач TOEFL" },
        { "date": "2026-05-15", "num": 4, "status": "completed", "topic": "Разнообразие наук — решение типичных задач TOEFL" },
        { "date": "2026-05-20", "num": 5, "status": "completed", "topic": "Разнообразие наук — решение типичных задач TOEFL" },
        { "date": "2026-05-22", "num": 6, "status": "moved", "topic": "Перенос по инициативе Маши → провели как дополнительный вторник 02.06" },
        { "date": "2026-05-27", "num": 6, "status": "completed", "topic": "Научный микс — психология моря, атомная наука, квантовая физика" },
        { "date": "2026-05-29", "num": 7, "status": "completed", "topic": "Закрепление научного блока + история и архитектура" },
        { "date": "2026-06-02", "num": 8, "status": "completed", "topic": "Инструктажи и деловая среда (последний урок перед каникулами)" },
        { "date": "2026-06-15", "num": 8.5, "status": "self-study", "topic": "Лето · модуль 1 — Voyager L1 · Time, the watchmaker, neutrinos", "homework": { "module_url": "https://newgeneration-english.ru/lingua-boost-lab/b2-plus/voyager-l1-time-travel/?v=v7", "module_title": "🌌 Открыть Voyager L1 · Time", "text": "Самостоятельная работа лета. 8 секций · MP3 listening · lex-gram cloze · sentence transformation · IELTS/Olympiad speaking. Пройди в спокойном темпе до 30.06." } },
        { "date": "2026-06-30", "num": 9, "status": "planned", "topic": "Летняя контрольная встреча #1 — разбор Voyager L1 + новая мини-тема" },
        { "date": "2026-07-15", "num": 9.5, "status": "self-study", "topic": "Лето · модуль 2 — Voyager L2 · Are we alone? (SETI quest)", "homework": { "module_url": "https://newgeneration-english.ru/lingua-boost-lab/b2-plus/voyager-l2-are-we-alone/", "module_title": "🛸 Открыть Voyager L2 · Are we alone?", "text": "Второй летний модуль. SETI-quest в Атакаме · Reyes + Aaron + логбук деда-часовщика из L1. 3 новых формата заданий vs L1 — matching headings, word formation, listening sentence completion." } },
        { "date": "2026-07-30", "num": 10, "status": "planned", "topic": "Летняя контрольная встреча #2 — разбор Voyager L2 + новая мини-тема" },
        { "date": "2026-08-15", "num": 10.5, "status": "self-study", "topic": "Лето · модуль 3 — тема уточняется (Voyager L3 или TOEFL-практика)", "schedule_note": "согласуем после июльской встречи" },
        { "date": "2026-08-27", "num": 11, "status": "planned", "topic": "Летняя контрольная встреча #3 — финальный разбор, настройка на сентябрь" }
      ]
    },
    {
      "id": "sova-elena",
      "notion_id": "34d7364c-ba79-81ba-b4d6-e8b07e6ed7f7",
      "name": "Сова Елена Витальевна",
      "level": "A2",
      "format": "индивидуально",
      "schedule": "вторник 19:00",
      "goal": "взрослый ученик, медленный темп, через карточки и опоры",
      "price_per_lesson": 2000,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contact_passport": "4524 №179806 (ГУ МВД по г.Москве, 20.06.2024)",
      "contact_phone": "+79671403548",
      "contact_email": "elenavit-2005@mail.ru",
      "contact_address": "105203, Москва, ул. Первомайская, д.113, кв.29",
      "pin": "2547",
      "lessons_in_package": 7,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 4,
      "stability_note": "Май-абонемент 7 уроков (вт 19:00): 4 проведены + 3 оплачены вперёд. Все даты — регулярные вторники, без сдвигов. 28.04→19.05 = первые 4 (grammar×2 + Wind in the Willows + SIM/coffee сегодня). 26.05/2.06/9.06 — оставшиеся 3.",
      "lessons": [
        { "date": "2026-04-28", "num": 1, "status": "completed", "topic": "Грамматика #1: simple + perfect tenses" },
        { "date": "2026-05-05", "num": 2, "status": "completed", "topic": "Грамматика #2: passive voice + past perfect" },
        { "date": "2026-05-12", "num": 3, "status": "completed", "topic": "The Wind in the Willows — чтение книги для детей, лексика, обсуждение" },
        { "date": "2026-05-19", "num": 4, "status": "completed", "topic": "SIM-карты и кофе — практическая лексика и диалоги" },
        { "date": "2026-05-26", "num": 5, "status": "planned", "topic": "" },
        { "date": "2026-06-02", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-06-09", "num": 7, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "sova-ekaterina",
      "notion_id": "34d7364c-ba79-810e-ac5b-f35b5a113898",
      "name": "Сова Екатерина",
      "nickname": "Катя",
      "summer_vacation": true,
      "summer_vacation_note": "На каникулах до сентября 2026 (с 19.05.2026)",
      "level": "B1",
      "format": "индивидуально",
      "schedule": "понедельник 18:00 (на каникулах)",
      "stability_note": "На 19.05.2026 отпущена на каникулы. Запланированные уроки на этой неделе не проводятся. Возобновление — уточнить с родителем.",
      "payment_status": "Оплачено",
      "parent_name": "Сова Елена Витальевна",
      "parent_passport": "4524 №179806",
      "parent_phone": "+79671403548",
      "parent_email": "elenavit-2005@mail.ru",
      "parent_address": "105203, Москва, ул. Первомайская, д.113, кв.29",
      "pin": "6924",
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 4,
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "completed", "topic": "ОГЭ / ЕГЭ — повторение лексики и формат экзамена" },
        { "date": "2026-05-11", "num": 2, "status": "completed", "topic": "Книги — жанры, рассказы, лексика" },
        { "date": "2026-05-18", "num": 3, "status": "completed", "topic": "Неправильные глаголы с предлогом — отработка форм и употребление" },
        { "date": "2026-05-25", "num": 4, "status": "completed", "topic": "Финальное повторение завершено — все слова, темы, книжки. На каникулы до сентября." }
      ]
    },
    {
      "id": "fedor-protasov",
      "notion_id": "34d7364c-ba79-8135-bda3-f409c1cf93a2",
      "name": "Фёдор Протасов",
      "level": "",
      "format": "индивидуально",
      "schedule": "вторник 16:00 / четверг 20:00 / пятница 20:00 / воскресенье 14:40",
      "goal": "Spotlight 9 + страны + Past Simple irregular + there is/are/was/were",
      "level": "A2/B1",
      "lessons_in_package": 13,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 7,
      "payment_status": "Оплачено",
      "payment_note": "Мария Петровна платит еженедельно",
      "parent_name": "Протасова Мария Петровна",
      "contract_note": "бумажный договор, не онлайн",
      "pin": "7186",
      "stability_note": "Расписание актуализировано 19.05.2026: вт 16:00 / чт 20:00 (раньше 20:15) / пт 20:00 + добавилось воскресенье 14:40 (после Дениса и пары). Май-абонемент: 6 проведено (1, 2, 3, 4, 5, 8), 14/15.05 перенесены на 17.05 — Pinocchio комбинированный.",
      "lessons": [
        { "date": "2026-05-01", "num": 1, "status": "completed", "topic": "Туристический английский — Китай (лексика, клише)" },
        { "date": "2026-05-05", "num": 2, "status": "completed", "topic": "Туристический английский — Италия" },
        { "date": "2026-05-07", "num": 3, "status": "completed", "topic": "Грамматический юнит" },
        { "date": "2026-05-08", "num": 4, "status": "completed", "topic": "Повторение неправильных глаголов" },
        { "date": "2026-05-12", "num": 5, "status": "completed", "topic": "Туристические клише" },
        { "date": "2026-05-14", "num": 6, "status": "rescheduled", "topic": "Перенесён на 17.05 (технические трудности)" },
        { "date": "2026-05-15", "num": 7, "status": "rescheduled", "topic": "Перенесён на 17.05 (технические трудности)" },
        { "date": "2026-05-17", "num": 8, "status": "completed", "topic": "Pinocchio (комбинированный за 14 и 15.05) — чтение, простейшие слова, работа с книгой" },
        { "date": "2026-05-19", "num": 9, "status": "completed", "topic": "Древний Китай — лексика, история, обсуждение" },
        { "date": "2026-05-21", "num": 10, "status": "planned", "topic": "" },
        { "date": "2026-05-22", "num": 11, "status": "planned", "topic": "" },
        { "date": "2026-05-26", "num": 12, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 13, "status": "planned", "topic": "" },
        { "date": "2026-05-29", "num": 14, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "ivanov-ivan",
      "notion_id": "3537364c-ba79-813d-a84b-ee42fad1bd19",
      "name": "Иванов Иван",
      "nickname": "Иван",
      "level": "B1+/B2",
      "format": "индивидуально",
      "duration": "1 час",
      "schedule": "плавающий — договариваемся еженедельно",
      "price_per_lesson": 2500,
      "monthly_package": 10000,
      "lessons_in_package": 4,
      "subscription_month": "2026-06",
      "lessons_used_this_month": 1,
      "payment_status": "Оплачено",
      "payment_note": "Июнь оплачен полностью: 4 урока × 2 500 ₽ = 10 000 ₽. Формат — 1 час, даты согласовываются по неделе.",
      "stability_note": "Май закрыт: 4 проведено + 1 пропуск. Июньский абонемент 4 урока по часу, формат серии Voyager (B2-plus, time-travel/space-themed). На 02.06 проведён L1. Дальше — L2 Are we alone?, затем L3, L4 по согласованию.",
      "parent_name": "Подлесных Татьяна Анатольевна",
      "parent_passport": "4524 514335 (06.11.2024)",
      "parent_phone": "+79057502111",
      "parent_email": "ryabina8@list.ru",
      "parent_address": "Москва, пос. Сосенское, п. Коммунарка, ул. Ясная, д.5, кв.33",
      "pin": "7670",
      "lessons": [
        { "date": "2026-05-01", "num": 1, "status": "completed", "topic": "Чтение — художественные тексты про путешествия во времени" },
        { "date": "2026-05-08", "num": 2, "status": "completed", "topic": "Аудирование академического уровня + новая лексика" },
        { "date": "2026-05-15", "num": 3, "status": "completed", "topic": "Грамматика — целенаправленная подготовка к МЦК" },
        { "date": "2026-05-22", "num": 4, "status": "missed", "topic": "Пропуск (Иван проспал)" },
        { "date": "2026-05-29", "num": 5, "status": "completed", "topic": "Устная практика — летние планы и каникулы" },
        { "date": "2026-06-02", "num": 1, "status": "completed", "topic": "Voyager L1 · Time travel + The Watchmaker's Apology + Neutrinos (B2-plus, lex-gram cloze, IELTS/Olympiad speaking)", "homework": { "text": "Открыть урок повторно: Use of English (cloze + transformation), Mini-writing, Olympiad Speaking. Reading T/F/NG в Homework — для тренировки close reading.", "module_url": "../lingua-boost-lab/b2-plus/voyager-l1-time-travel/?v=v7", "module_title": "Voyager L1 · Time" } },
        { "date": "2026-06-09", "num": 2, "status": "planned", "topic": "Voyager L2 · Are we alone? — SETI quest at the Atacama outpost (B2-plus, Reading matching headings, Word formation, Listening sentence completion)", "schedule_note": "дата уточняется — согласовываем за неделю", "homework": { "module_url": "https://newgeneration-english.ru/lingua-boost-lab/b2-plus/voyager-l2-are-we-alone/", "module_title": "🛸 Открыть Voyager L2 · Are we alone?", "text": "8 секций · 2 MP3 (лекция Drake/Fermi + final broadcast Reyes) · Mia's grandfather's logbook возвращается из L1." } },
        { "date": "2026-06-16", "num": 3, "status": "planned", "topic": "Voyager L3 — тема уточняется", "schedule_note": "дата уточняется" },
        { "date": "2026-06-23", "num": 4, "status": "planned", "topic": "Voyager L4 — тема уточняется", "schedule_note": "дата уточняется" }
      ]
    },
    {
      "id": "daniella-libova",
      "notion_id": "34d7364c-ba79-81af-9ba9-f423aede5524",
      "name": "Даниэлла Либова",
      "level": "B2+",
      "format": "индивидуально",
      "schedule": "понедельник 18:00 / четверг 18:00",
      "goal": "подготовка к ЕГЭ (word formation, exam speaking)",
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 4,
      "stability_note": "Май-абонемент 8 уроков. Отыграно 4 (4, 7, 11, 18 completed). На неделе 19-25.05 уроков нет (плавающий график). Дальше 21, 25, 28 — времена под подтверждение. Расписание плавающее → нужна редактируемость через кабинет (open issue).",
      "payment_status": "Оплачено",
      "parent_name": "Либова Юлия Игоревна",
      "contract_note": "без договора",
      "pin": "5376",
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "completed", "topic": "Speaking — устная практика, разговорная часть" },
        { "date": "2026-05-07", "num": 2, "status": "completed", "topic": "Speaking — устная практика (продолжение)" },
        {
          "date": "2026-05-11", "num": 3, "status": "completed", "topic": "ЕГЭ-практика — устные части, разбор заданий",
          "homework": {
            "text": "Пройти Word Building (префиксы и суффиксы) — упражнения 1 и 2. К следующему уроку.",
            "module_url": "../lingua-boost-lab/b1/word-building-prefixes-and-suffixes.html",
            "module_title": "Word Building"
          }
        },
        { "date": "2026-05-14", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-18", "num": 5, "status": "completed", "topic": "Battle of Levels — чтение из учебника Музлановой (трудный текст)" },
        { "date": "2026-05-21", "num": 6, "status": "cancelled", "topic": "Отменено — Даниэлла не сможет (Маша подтвердила 20.05)" },
        { "date": "2026-05-25", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "denis-shalmanov",
      "greeting_student": "Здравствуйте, Денис",
      "greeting_parent": "Здравствуйте, Денис",
      "notion_id": "34d7364c-ba79-81a5-bdd8-ce47d7b050d7",
      "name": "Денис Шалманов",
      "level": "A1",
      "format": "индивидуально",
      "schedule": "воскресенье 10:30",
      "price_per_lesson": 2500,
      "monthly_package": 10000,
      "payment_status": "Оплачено",
      "payment_note": "Июнь оплачен полностью (10 000 ₽, 4 урока × 2 500) — 31.05.2026. Май закрыт.",
      "is_adult": true,
      "parent_name": "",
      "contract_note": "отсканированный договор, требует визуальной сверки",
      "pin": "6347",
      "lessons_in_package": 4,
      "subscription_month": "2026-06",
      "lessons_used_this_month": 0,
      "stability_note": "Май закрыт полностью (5 уроков проведены). Июнь оплачен 31.05.2026: 4 воскресенья × 2 500 ₽ = 10 000 ₽. Стабильный темп без скачков и откатов.",
      "lessons": [
        { "date": "2026-05-03", "num": 1, "status": "completed", "topic": "Одежда — лексика и описания" },
        { "date": "2026-05-10", "num": 2, "status": "completed", "topic": "Present Simple / Present Continuous + базовые конструкции" },
        { "date": "2026-05-17", "num": 3, "status": "completed", "topic": "Дома — лексика, описания, что есть дома" },
        { "date": "2026-05-24", "num": 4, "status": "completed", "topic": "Повторение темы «дома» (закрепление)" },
        { "date": "2026-05-31", "num": 5, "status": "completed", "topic": "Город — лексика, городские объекты" },
        { "date": "2026-06-07", "num": 6, "status": "planned", "topic": "Город — расширяем городскую лексику, описания" },
        { "date": "2026-06-14", "num": 7, "status": "planned", "topic": "Шоппинг в городе — фразы для магазина (Can I have / How much is / I would like)" },
        { "date": "2026-06-21", "num": 8, "status": "planned", "topic": "Направления в городе — Go straight / Turn left, right / It is near" },
        { "date": "2026-06-28", "num": 9, "status": "planned", "topic": "Кофе в городе — заказ кофе (I would like a cappuccino / To go please)" }
      ]
    },
    {
      "id": "anya-isaeva",
      "notion_id": "34d7364c-ba79-8199-879a-d0400012561e",
      "name": "Аня Исаева",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 17:00",
      "price_per_lesson": 2500,
      "payment_status": "Оплачено",
      "parent_name": "Исаева Наталья Вячеславовна",
      "parent_passport": "4514 567410 (УФМС России по г.Москве)",
      "parent_email": "platemir@yandex.ru",
      "parent_address": "Москва, Береговой пр-д, д.7, кв.95",
      "pin": "2512",
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 3,
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "completed", "topic": "Города — конкретная лексика, заканчивали тему" },
        { "date": "2026-05-11", "num": 2, "status": "completed", "topic": "Present Perfect — теория и Speaking по нему" },
        { "date": "2026-05-18", "num": 3, "status": "completed", "topic": "Города — функции города (городские объекты) + Present Continuous в контексте" },
        { "date": "2026-05-25", "num": 4, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "yulya-lushina",
      "greeting_student": "Привет, Юлия",
      "notion_id": "34d7364c-ba79-81b5-8215-fdfe91bec709",
      "name": "Юля Лушина",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 12:00",
      "stability_note": "Понедельник 12:00. На неделе 1-7 июня — разовый перенос на среду 3 июня.",
      "price_per_lesson": 2000,
      "payment_status": "Оплачено",
      "parent_name": "Лушин Александр Анатольевич",
      "pin": "2223",
      "lessons_in_package": 4,
      "subscription_month": "2026-06",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-18", "num": 1, "status": "completed", "topic": "Cute vampire English v1 (Pre-A1) — face/body parts, HSKT video, friendly vampire family." },
        { "date": "2026-05-25", "num": 2, "status": "completed", "topic": "" },
        { "date": "2026-06-01", "num": 3, "status": "rescheduled", "topic": "Перенос с понедельника на среду 3 июня (по договорённости)." },
        {
          "date": "2026-06-03",
          "num": 4,
          "status": "planned",
          "topic": "Vampire English v8 — Music & Friends (Pre-A1, 90 min).",
          "homework": {
            "module_url": "../lingua-boost-lab/pre-a1/julia-vampire/index.html?v=1",
            "module_title": "🦇 Открыть урок",
            "text": "Откройте на айпаде, нажимайте на картинки и значки 🔊 — всё озвучено."
          }
        },
        { "date": "2026-06-08", "num": 5, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "yulya-izotova",
      "greeting_student": "Привет, Юлия",
      "notion_id": "34d7364c-ba79-81fa-8d1b-ed43ce161b3b",
      "name": "Юля Изотова",
      "level": "A1+",
      "format": "индивидуально",
      "schedule": "понедельник 16:00 / пятница 15:30",
      "goal": "Старлайт 3 / Past Simple, неправильные глаголы, лексика по темам",
      "price_per_lesson": 2000,
      "monthly_package": 18000,
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 5,
      "payment_status": "Оплачено",
      "parent_name": "Изотова Ольга Игоревна",
      "parent_passport": "4510 764054",
      "parent_phone": "+79269754602",
      "parent_email": "meet.me.here@mail.ru",
      "pin": "2799",
      "stability_note": "Май-абонемент 8 уроков (оплачено 8). На 18.05 отыграно 5 (1, 4, 8, 15, 18). 11 мая — пропуск, не в счёт. Дальше 22, 25, 29.",
      "lessons": [
        { "date": "2026-05-01", "num": 1, "status": "completed", "topic": "еда — лексика" },
        { "date": "2026-05-04", "num": 2, "status": "completed", "topic": "магазины + история про Юлию (чтение, лексика)" },
        { "date": "2026-05-08", "num": 3, "status": "completed", "topic": "контейнеры/бутылки/банки + Present Simple" },
        { "date": "2026-05-11", "num": 0, "status": "missed", "topic": "Пропуск (не в счёт абонемента)" },
        { "date": "2026-05-15", "num": 4, "status": "completed", "topic": "неправильные глаголы, времена, истории" },
        { "date": "2026-05-18", "num": 5, "status": "completed", "topic": "Swimming pool — лексика и активности (бассейн)" },
        { "date": "2026-05-22", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-25", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-29", "num": 8, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "sofia-pavlova",
      "greeting_student": "Привет, София",
      "notion_id": "34d7364c-ba79-817f-85f8-c6f87fd4d85c",
      "name": "Соня Павлова",
      "level": "B2/B2+",
      "format": "индивидуально",
      "schedule": "четверг 17:00",
      "price_per_lesson": 2000,
      "monthly_package": 8000,
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "goal": "ЕГЭ: лексика B2+, word formation, writing, speaking",
      "payment_status": "Оплачено",
      "payment_note": "Полностью оплачено в мае (вторая половина 4 000 ₽ внесена 20.05.2026)",
      "summer_vacation": true,
      "summer_vacation_note": "После 28.05 — на летние каникулы до сентября 2026",
      "parent_name": "Анатольева Галина Анатольевна",
      "parent_passport": "45 24 № 708384 (ГУ МВД по г.Москве)",
      "parent_address": "Москва, Зельев переулок, д.3, кв.4",
      "contract_note": "подписан мамой с критическими пометками жёлтым; дата не проставлена; мама хочет править формулировки",
      "pin": "9972",
      "lessons": [
        { "date": "2026-05-07", "num": 1, "status": "planned", "topic": "ЕГЭ: повторение лексики апреля + word formation / vocabulary MCQ" },
        { "date": "2026-05-14", "num": 2, "status": "planned", "topic": "Reading B2 / B2+: тематический текст + вопросы ЕГЭ" },
        { "date": "2026-05-21", "num": 3, "status": "planned", "topic": "Writing / email: структура, ответы, собственные вопросы" },
        { "date": "2026-05-28", "num": 4, "status": "planned", "topic": "Speaking + grammar consolidation: времена, passive, modals" }
      ]
    },
    {
      "id": "ekaterina-mariya-pair",
      "notion_id": "34d7364c-ba79-81f0-ba7f-d87dcd7dfd19",
      "name": "Екатерина и Мария",
      "archived": true,
      "archived_note": "Разнесён на 2 отдельных кабинета 20.05.2026: ekaterina-medvedeva-solo (PIN 3714) + maria-kuznetsova-solo (PIN 3715). Запись оставлена для legacy-данных (отчёты, прежние логи).",
      "level": "",
      "format": "парное занятие",
      "schedule": "четверг 18:00 / воскресенье 13:35",
      "price_per_lesson": 1500,
      "monthly_package": 12000,
      "payment_status": "Ожидает",
      "payment_note": "Лихолева Елена (мама Маши) должна половину пакета",
      "stability_note": "Пара не подтвердила завтра четверг 21.05 — статус под вопросом (на 20.05.2026)",
      "parent_name": "Медведева Марина Сергеевна (Катя) / Лихолева Елена Сергеевна (Маша)",
      "kids": [
        {
          "name": "Медведева Екатерина",
          "parent": "Медведева Марина Сергеевна",
          "parent_passport": "4523 521762 (04.05.2023)",
          "parent_phone": "+79165478727",
          "parent_email": "marine_medvedeva@rambler.ru",
          "parent_address": "Москва, ул. Островитянова, д.9 кв.947"
        },
        {
          "name": "Кузнецова Мария",
          "parent": "Лихолева Елена Сергеевна",
          "parent_passport": "4519 568773 (ГУ МВД России по г.Москве)",
          "parent_email": "ivan-tenaivanova@ya.ru (уточнить)",
          "parent_address": "Москва, ул. Акад. Волгина, д.8А"
        }
      ],
      "pin": "3713",
      "lessons_in_package": 9,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 5,
      "lessons": [
        { "date": "2026-05-03", "num": 1, "status": "completed", "topic": "Введение / повторение всех грамматических тем" },
        { "date": "2026-05-07", "num": 2, "status": "completed", "topic": "Повторение и конспекты" },
        { "date": "2026-05-10", "num": 3, "status": "completed", "topic": "Праздники и дни рождения — лексика, диалоги" },
        { "date": "2026-05-14", "num": 4, "status": "completed", "topic": "Petting — вариант 4 или 5 (формулировку точно уточнить)" },
        { "date": "2026-05-17", "num": 5, "status": "completed", "topic": "Экология — введение темы" },
        { "date": "2026-05-21", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-24", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "" },
        { "date": "2026-05-31", "num": 9, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "ekaterina-medvedeva-solo",
      "notion_id": "",
      "name": "Катя Медведева",
      "greeting_student": "Привет, Екатерина",
      "greeting_parent": "Здравствуйте, Марина",
      "level": "B1",
      "format": "индивидуально (раздельно с Машей с 28.05)",
      "schedule": "четверг 18:00 / воскресенье 13:35",
      "stability_note": "С 28.05.2026 переходят на раздельный формат: Катя — 18:00, Маша — 19:00. Завтрашний урок 21.05 не подтверждён → переносится на 28.05.",
      "price_per_lesson": 1500,
      "monthly_package": 6000,
      "lessons_in_package": 9,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 5,
      "payment_status": "Оплачено",
      "payment_note": "Марина Сергеевна оплатила свою половину пакета",
      "parent_name": "Медведева Марина Сергеевна",
      "parent_passport": "4523 521762 (04.05.2023)",
      "parent_phone": "+79165478727",
      "parent_email": "marine_medvedeva@rambler.ru",
      "parent_address": "Москва, ул. Островитянова, д.9 кв.947",
      "pin": "3714",
      "pair_origin": "ekaterina-mariya-pair",
      "lessons": [
        { "date": "2026-05-03", "num": 1, "status": "completed", "topic": "Введение / повторение всех грамматических тем" },
        { "date": "2026-05-07", "num": 2, "status": "completed", "topic": "Повторение и конспекты" },
        { "date": "2026-05-10", "num": 3, "status": "completed", "topic": "Праздники и дни рождения — лексика, диалоги" },
        { "date": "2026-05-14", "num": 4, "status": "completed", "topic": "Petting — вариант 4 или 5 (формулировку точно уточнить)" },
        { "date": "2026-05-17", "num": 5, "status": "completed", "topic": "Экология — введение темы" },
        { "date": "2026-05-21", "num": 6, "status": "rescheduled", "topic": "Перенос на 28.05 — не подтвердили завтра" },
        { "date": "2026-05-24", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "Первый раздельный урок (Катя — 18:00)" },
        { "date": "2026-05-31", "num": 9, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "maria-kuznetsova-solo",
      "notion_id": "",
      "name": "Маша Кузнецова",
      "greeting_student": "Привет, Мария",
      "greeting_parent": "Здравствуйте, Елена",
      "level": "B1",
      "format": "индивидуально (раздельно с Катей с 28.05)",
      "schedule": "четверг 19:00 / воскресенье 13:35",
      "stability_note": "С 28.05.2026 переходят на раздельный формат: Маша — 19:00, Катя — 18:00. Завтрашний урок 21.05 не подтверждён → переносится на 28.05.",
      "price_per_lesson": 1500,
      "monthly_package": 6000,
      "lessons_in_package": 9,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 5,
      "payment_status": "Ожидает",
      "payment_note": "Елена Сергеевна должна свою половину пакета (6 000 ₽)",
      "parent_name": "Лихолева Елена Сергеевна",
      "parent_passport": "4519 568773 (ГУ МВД России по г.Москве)",
      "parent_email": "ivan-tenaivanova@ya.ru (уточнить)",
      "parent_address": "Москва, ул. Акад. Волгина, д.8А",
      "pin": "3715",
      "pair_origin": "ekaterina-mariya-pair",
      "lessons": [
        { "date": "2026-05-03", "num": 1, "status": "completed", "topic": "Введение / повторение всех грамматических тем" },
        { "date": "2026-05-07", "num": 2, "status": "completed", "topic": "Повторение и конспекты" },
        { "date": "2026-05-10", "num": 3, "status": "completed", "topic": "Праздники и дни рождения — лексика, диалоги" },
        { "date": "2026-05-14", "num": 4, "status": "completed", "topic": "Petting — вариант 4 или 5 (формулировку точно уточнить)" },
        { "date": "2026-05-17", "num": 5, "status": "completed", "topic": "Экология — введение темы" },
        { "date": "2026-05-21", "num": 6, "status": "rescheduled", "topic": "Перенос на 28.05 — не подтвердили завтра" },
        { "date": "2026-05-24", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "Первый раздельный урок (Маша — 19:00)" },
        { "date": "2026-05-31", "num": 9, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "katya-marakina",
      "notion_id": "34d7364c-ba79-8173-a103-f60f2bb5f124",
      "name": "Катя Маракина",
      "level": "B1",
      "format": "индивидуально",
      "schedule": "вторник 17:00 + воскресенье 13:00 (по 90 мин)",
      "schedule_note": "Время воскресенья перенесено 12:00 → 13:00 по просьбе мамы (с июня). Маша думает над форматом — 13:00 в выходной перебивает день; возможно вернёмся к 12:00 или другому окну.",
      "price_per_lesson": 2500,
      "monthly_package": 20000,
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 4,
      "stability_note": "Май-июнь абонемент 8 уроков (4 вт + 4 вс) до 14.06.2026. Старт 19.05.2026. С 14.06 — летний пересбор (родители просят остаться на лето; Маша решает). Проведено 4 из 8 (Jerusalem 31.05 закрыт). История: 26.04, 3.05, 10.05 cancelled (согласованные), 17.05 missed (без предупреждения).",
      "payment_status": "Оплачено",
      "parent_name": "Кедрова Татьяна Владимировна",
      "parent_passport": "45 08 445532",
      "parent_address": "Москва, Сиреневый б-р, д.44, корп.1, кв.163",
      "pin": "1265",
      "lessons": [
        { "date": "2026-04-26", "num": 0, "status": "cancelled", "topic": "Согласованный перенос (история до абонемента)" },
        { "date": "2026-05-03", "num": 0, "status": "cancelled", "topic": "Согласованный перенос (история до абонемента)" },
        { "date": "2026-05-10", "num": 0, "status": "cancelled", "topic": "Согласованный перенос (история до абонемента)" },
        { "date": "2026-05-17", "num": 0, "status": "missed", "topic": "Пропуск без предупреждения (история до абонемента)" },
        { "date": "2026-05-19", "num": 1, "status": "completed", "topic": "Времена, техники решения ОГЭ" },
        { "date": "2026-05-24", "num": 2, "status": "completed", "topic": "Кулинария и времена, страны мира" },
        { "date": "2026-05-25", "num": 3, "status": "completed", "topic": "Италия: известные люди, чудеса света + немного про Ирландию" },
        { "date": "2026-05-31", "num": 4, "status": "completed", "topic": "Jerusalem — A City of Three Faiths (speaking-focus, Would, Modals)", "homework": { "module_url": "../lingua-boost-lab/b1/jerusalem-three-faiths/?v=4cbcbaf", "module_title": "Открыть урок Jerusalem", "text": "Интерактивный B1-урок: 17 секций, аудио, говорение, Would-конструкции, модальные глаголы. Можно открыть до занятия — пробежаться по vocabulary, дать ушам привыкнуть к narrator-аудио." } },
        { "date": "2026-06-02", "num": 5, "status": "planned", "topic": "Тема уточняется", "schedule_note": "вторник 17:00 — тему согласовываем с Машей" },
        { "date": "2026-06-07", "num": 6, "status": "planned", "topic": "Switzerland · Mountains & Chocolate — часть 1 (B1, redesign под Unbounded, hero Маттерхорн+шоколад+часы)", "homework": { "module_url": "../lingua-boost-lab/b1/switzerland-mountains-chocolate/?v=v2", "module_title": "Открыть урок Switzerland · часть 1", "text": "Интерактивный B1-урок про Швейцарию. На уроке покрываем Watch-first блок (история Швейцарии), reading и vocabulary первой половины. На следующий урок — продолжение." } },
        { "date": "2026-06-09", "num": 7, "status": "planned", "topic": "Тема уточняется", "schedule_note": "вторник 17:00 — тему согласовываем с Машей" },
        { "date": "2026-06-14", "num": 8, "status": "planned", "topic": "Switzerland · Mountains & Chocolate — часть 2 (B1, последний урок до летнего пересбора)", "homework": { "module_url": "../lingua-boost-lab/b1/switzerland-mountains-chocolate/?v=v2", "module_title": "Открыть урок Switzerland · часть 2", "text": "Завершаем Switzerland-урок: оставшиеся секции, синтез, mini-writing. Последний урок текущего абонемента до летнего пересбора." } }
      ]
    }
  ],
  "reports": [
    {
      "id": "2026-05-anya-isaeva-parent",
      "student_id": "anya-isaeva",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Аня молодец: закончили блок по теме города, ввели Present Perfect и закрепили три формы настоящего времени — Present Simple, Present Continuous и Present Perfect. Прописали диктант; дальше — города, другие страны, спорт и travelling.",
      "content": "# Краткий вывод\n\nАня прошла первый блок занятий по понедельникам. Основной фокус был на устной базе, простых личных вопросах, there is / there are, предлогах места и городской лексике. Устная речь начала становиться увереннее: пауз меньше, фразы собираются ровнее, но грамматические конструкции нужно доводить до автоматизма.\n\n# Сегодня, 11 мая\n\nАня молодец: закончили блок по теме города, ввели Present Perfect и собрали три формы настоящего времени — Present Simple, Present Continuous и Present Perfect. Прописали диктант. Дальше переходим к полезным новым темам: города, другие страны, спорт и travelling.\n\n# Следующий фокус\n\nЗакрепление Present Simple / Present Continuous / Present Perfect через устную практику, диктанты и новые темы: города, другие страны, спорт и travelling.",
      "notion_url": "https://www.notion.so/35a7364cba7981b787b5cf8960ca9354"
    },
    {
      "id": "2026-05-denis-shalmanov-student",
      "student_id": "denis-shalmanov",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "student report",
      "recipient": "Денис Шалманов",
      "status": "ready to send",
      "title": "2026-05 — Денис Шалманов — student report",
      "short_message": "Денис, спасибо за стабильный темп в мае! Все 5 воскресений проведены: одежда → Present Simple/Continuous → дома → повтор домов → город. Май закрыт полностью, ничего не должны. К оплате за июнь — 10 000 ₽ (4 урока × 2 500).",
      "content": "Добрый день!\n\nОтправляю краткий отчёт по нашим занятиям за май.\n\n# Календарь занятий — май (5 занятий)\n\n- **3 мая** — Одежда: лексика, описания (завершали тему)\n- **10 мая** — Past Simple / Past Continuous, stative verbs\n- **17 мая** — Дома: лексика, описания\n- **24 мая** — *запланирован*\n- **31 мая** — *запланирован*\n\n3 из 5 проведены, 2 впереди.\n\n# По прогрессу\n\n**Мы** идём в стабильном темпе. Темы по бытовой лексике хорошо ложатся, грамматику времён (Past Simple, Past Continuous, stative verbs) разбираем основательно. Видно, что вы спокойно осваиваете новый материал и активно работаете на уроке.\n\n# Зоны роста\n\n- Вывод изученной лексики в свободную речь (пока больше в распознавании)\n- Автоматизм времён — особенно различение Past Simple vs Past Continuous в потоке\n- Расширение бытовой тематики (работа, транспорт, дорога)\n\n# Следующая задача\n\n**Вам** стоит чаще проговаривать новые слова и темы вслух между уроками — даже 10–15 минут речи о прошедшем дне в Past Simple дают сильный эффект. На уроках **мы** продолжаем тематические блоки + закрепление времён в свободной речи.\n\n# Майский абонемент\n\n5 воскресений мая (3, 10, 17, 24, 31). Стоимость занятия 2 500 ₽.\n\n- Оплачено 7 500 ₽ (3 урока: 3, 10, 17) + 2 переноса с апреля\n- К оплате за 24 и 31 мая: **5 000 ₽**\n",
      "notion_url": "https://www.notion.so/3637364cba7981a98085ef806ef7deb2"
    },
    {
      "id": "2026-05-yulya-izotova-parent",
      "student_id": "yulya-izotova",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "Изотова Ольга Игоревна",
      "status": "ready to send",
      "title": "2026-05 — Юля Изотова — parent report",
      "short_message": "Юля стабильно идёт вперёд: 4 из 9 уроков проведены (еда, магазины, контейнеры, неправильные глаголы). Формат историй работает особенно хорошо. Один пропуск 11 мая, 4 урока впереди (18, 22, 25, 29).",
      "content": "Добрый день!\n\nОтправляю краткий отчёт по занятиям **Юли** за май.\n\n# Календарь занятий — май (9 занятий)\n\n- **1 мая** — Еда: лексика\n- **4 мая** — Магазины + история про Юлию (чтение, лексика)\n- **8 мая** — Контейнеры / бутылки / банки + Present Simple\n- **11 мая** — *пропуск*\n- **15 мая** — Неправильные глаголы, времена, истории\n- **18 мая** — *запланирован*\n- **22 мая** — *запланирован*\n- **25 мая** — *запланирован*\n- **29 мая** — *запланирован*\n\n4 из 9 проведены, 1 пропуск, 4 впереди.\n\n# По прогрессу\n\nЮля стабильно идёт вперёд. Формат историй и сюжетных занятий работает особенно хорошо: через них лучше запоминается и грамматика, и тематическая лексика. На занятиях много чтения и новых слов, Юля включена.\n\n# Зоны роста\n\n- Вывод трёх времён (Present Simple, Present Continuous, Past Simple) в собственную речь — пока больше в распознавании\n- Закрепление неправильных глаголов (повторяем регулярно, нужна автоматизация)\n- Расширение тематической лексики через короткие связные истории\n\n# Следующая задача\n\nПродолжаем закреплять грамматику через истории, делаем больше устной практики. До конца мая — 4 занятия. Юле стоит каждый раз короткими историями использовать новые слова и неправильные глаголы.\n\n# Майский абонемент — 9 занятий\n\nПонедельники и пятницы. Стоимость занятия 2 000 ₽. Итого: **18 000 ₽** (оплачено).\n\nОдин пропуск 11 мая остаётся непроведённым — при возможности можем отработать или переоформить как перенос.\n",
      "notion_url": "https://www.notion.so/3637364cba798136a342cf0593982b17"
    },
    {
      "id": "2026-05-katya-sova-parent",
      "student_id": "sova-ekaterina",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Катя стабильно работает на уровне B1. В мае фокус — books / book genres, phrasal verbs и ОГЭ-формат; важно фиксировать ошибки и выводить лексику в речь.",
      "content": "# Краткий вывод\n\nКатя работает на уровне B1. Основные блоки: ОГЭ-формат, books / book genres и phrasal verbs.\n\n# Ближайший фокус\n\nBook genres → vocabulary table → questions → B1 multiple choice → matching → interview → short result check.",
      "notion_url": "https://www.notion.so/35a7364cba7981a2801af0ed869d847f"
    },
    {
      "id": "2026-05-ekaterina-medvedeva-parent",
      "student_id": "ekaterina-mariya-pair",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель (Екатерина Медведева)",
      "status": "source imported",
      "title": "Отчёт родителю Екатерины · май 2026",
      "short_message": "Катя работала ровно и стабильно: word formation, suffixes/prefixes, gerund/infinitive, used to и ОГЭ. Speaking стал собраннее, лучше держится фрейм.",
      "content": "# Краткий вывод\n\nКатя работала ровно и стабильно. Понимание тем стало лучше, speaking подрос.\n\n# Май\n\n9 занятий × 1 500 руб. = 13 500 руб.",
      "notion_url": "https://www.notion.so/35a7364cba7981bea07ddf8a902b1f13"
    },
    {
      "id": "2026-05-maria-kuznetsova-parent",
      "student_id": "ekaterina-mariya-pair",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель (Мария Кузнецова)",
      "status": "source imported",
      "title": "Отчёт родителю Марии · май 2026",
      "short_message": "Маша работает в паре с Катей. Нужна дополнительная опора на построение предложения и точечная практика: gerund/infinitive, word formation, spelling и более полные ответы.",
      "content": "# Краткий вывод\n\nМаша работает в паре с Катей и проходит те же темы. По последним работам точность временно просела: нужны опора на построение предложения и точечная практика.\n\n# Примечание\n\nОтдельной личной карточки Марии Кузнецовой не найдено, строка связана с общей карточкой пары Екатерина и Мария.",
      "notion_url": "https://www.notion.so/35a7364cba7981489de5fa224b04e372"
    },
    {
      "id": "2026-05-andrei-kruglov-toefl",
      "student_id": "andrei-kruglov",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "TOEFL diagnostic",
      "recipient": "родитель",
      "status": "source imported",
      "title": "TOEFL диагностика · 2026",
      "short_message": "Андрей показывает уверенный B2. TOEFL-style diagnostic estimate — 4.0/6.0. Сильные стороны Reading и Listening; фокус роста — Writing/Speaking accuracy.",
      "content": "# Краткий вывод\n\nАндрей показывает уверенный общий уровень B2. Диагностическая оценка по TOEFL iBT 2026 classroom scale — 4.0 из 6.0.\n\n# План\n\nReading, real-audio listening, email + academic discussion writing, structured speaking, collocations/articles/plurals.",
      "notion_url": "https://www.notion.so/35a7364cba79812492a3dcc970b5ceef"
    },
    {
      "id": "2026-05-daniella-libova-parent",
      "student_id": "daniella-libova",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "Юлия Игоревна",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Дана укрепляется: грамматика подросла, ответы стали ровнее. Сильные разделы — аудирование и чтение; зоны роста — spelling, word formation, speaking и writing по критериям ЕГЭ.",
      "content": "# Краткий вывод\n\nВ апреле Дана работала в формате подготовки к ЕГЭ: грамматика, словообразование, устная часть и диагностические задания. Подключали TOEFL-формат и Langart.\n\n# Май\n\n6 занятий к оплате после переноса 2 занятий из апреля.",
      "notion_url": "https://www.notion.so/35a7364cba7981ef858beda6387ad2f5"
    },
    {
      "id": "2026-05-yulya-lushina-parent",
      "student_id": "yulya-lushina",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Юля занимается в игровом формате. Главный прогресс — узнавание английского в понятных ситуациях, реакция на команды и повторение коротких фраз.",
      "content": "# Краткий вывод\n\nЮля занимается в игровом формате: движение, картинки, персонажи, игрушки и короткие повторяющиеся фразы.\n\n# Следующий фокус\n\nBody and face, This is my..., I have..., He/She/It has..., feelings, animals, actions.",
      "notion_url": "https://www.notion.so/35a7364cba79819c9339d3c4f4953e46"
    }
  ],
  "labModules": [
    { "level": "Pre-A1", "title": "Body & Grammar Garden", "url": "../lingua-boost-lab/pre-a1/body-and-grammar-pink.html" },
    { "level": "Pre-A1", "title": "Hello! Classroom Fun", "url": "../lingua-boost-lab/pre-a1/hello-classroom-fun.html" },
    { "level": "A1", "title": "Present Simple Routines", "url": "../lingua-boost-lab/a1/a1-01-present-simple-routines.html" },
    { "level": "A1", "title": "Present Simple Questions & Negatives", "url": "../lingua-boost-lab/a1/a1-02-present-simple-questions-negatives.html" },
    { "level": "A1", "title": "Present Simple + Adverbs of Frequency / There is/are", "url": "../lingua-boost-lab/a1/a1-03-present-simple-adverbs-frequency.html" },
    { "level": "A1", "title": "Have / Has — My Things", "url": "../lingua-boost-lab/a1/a1-04-have-has-my-things.html" },
    { "level": "A1", "title": "My / Your / His / Her", "url": "../lingua-boost-lab/a1/a1-05-my-your-his-her.html" },
    { "level": "A1", "title": "Prepositions of Place", "url": "../lingua-boost-lab/a1/a1-06-prepositions-of-place.html" },
    { "level": "A1", "title": "Instructions & Requests", "url": "../lingua-boost-lab/a1/a1-07-instructions-requests.html" },
    { "level": "A1", "title": "Final Mission (A1)", "url": "../lingua-boost-lab/a1/a1-08-final-mission.html" },
    { "level": "A1", "title": "Easter English Lesson", "url": "../lingua-boost-lab/a1/easter-english-lesson.html" },
    { "level": "A1", "title": "Past Simple Adventure", "url": "../lingua-boost-lab/a1/past-simple-adventure.html" },
    { "level": "A1", "title": "Prepositions World", "url": "../lingua-boost-lab/a1/prepositions-world.html" },
    { "level": "A1", "title": "School Words & Pronouns", "url": "../lingua-boost-lab/a1/school-words-and-pronouns.html" },
    { "level": "A2", "title": "Ancient China Explorer", "url": "../lingua-boost-lab/a2/ancient-china-explorer.html" },
    { "level": "A2", "title": "Core Trainer A2 → B1", "url": "../lingua-boost-lab/a2/core-trainer-a2-b1.html" },
    { "level": "A2", "title": "English Booster A2 → B1", "url": "../lingua-boost-lab/a2/english-booster-a2-b1.html" },
    { "level": "B1", "title": "Ancient China Cultural Studies", "url": "../lingua-boost-lab/b1/ancient-china-cultural-studies.html" },
    { "level": "B1", "title": "Grammar Arcade: Present Continuous vs Present Perfect", "url": "../lingua-boost-lab/b1/grammar-arcade-pc-pp.html" },
    { "level": "B1", "title": "Restaurant Menu Lab", "url": "../lingua-boost-lab/b1/restaurant-menu-lab.html" },
    { "level": "B1", "title": "Space Explorers", "url": "../lingua-boost-lab/b1/space-explorers-english.html" },
    { "level": "B1", "title": "Whispering Library Quest", "url": "../lingua-boost-lab/b1/whispering-library-quest.html" },
    { "level": "B1", "title": "Word Forge: Suffixes & Prefixes", "url": "../lingua-boost-lab/b1/word-building-prefixes-and-suffixes.html" },
    { "level": "B2+", "title": "Geo Quest: Articles on the Map", "url": "../lingua-boost-lab/b2-plus/articles-with-geographical-names.html" },
    { "level": "C1", "title": "Stars & Stellar Phenomena", "url": "../lingua-boost-lab/c1/stars-and-stellar-phenomena.html" }
  ],
  "contracts": {
    "andrei-kruglov": {
      "folder": "assets/contracts/andrei-kruglov",
      "files": ["01_договор_стр1.pdf", "02_договор_стр2_условия.pdf", "03_договор_стр3_подпись.jpg"]
    },
    "anya-isaeva": {
      "folder": "assets/contracts/anya-isaeva",
      "files": ["01_договор_стр1.webp", "02_договор_стр2_условия.webp", "03_договор_стр3_подпись.webp", "04_согласие_на_ПД.webp"]
    },
    "denis-shalmanov": {
      "folder": "assets/contracts/denis-shalmanov",
      "files": ["договор_отсканированный.pdf"]
    },
    "ivanov-ivan": {
      "folder": "assets/contracts/ivanov-ivan",
      "files": ["01_договор_стр1.jpeg", "02_договор_стр2_условия.jpeg", "03_договор_стр3_подпись.jpeg", "04_согласие_на_ПД.jpeg"]
    },
    "katya-marakina": {
      "folder": "assets/contracts/katya-marakina",
      "files": ["01_договор_стр1.jpeg", "02_договор_стр2.jpeg", "03_договор_стр3.jpeg", "04_доп.png"]
    },
    "sofia-pavlova": {
      "folder": "assets/contracts/sofia-pavlova",
      "files": ["01_согласие_на_ПД_с_пометками.jpg", "02_договор_стр1_подпись.jpg", "03_договор_стр1_дубль.jpg", "04_договор_стр1_низ.jpg", "05_договор_стр2_оплата.jpg", "06_договор_стр3_форс_мажор.jpg", "07_договор_стр4_срок.jpg", "08_дополнительная_страница.jpg"]
    },
    "sova-elena": {
      "folder": "assets/contracts/sova-family",
      "files": ["01_общий_договор.pdf", "02_договор_Катя_реквизиты.pdf", "03_реквизиты_Елена.png"],
      "note": "общий договор семьи Сова — Елена и Катя"
    },
    "sova-ekaterina": {
      "folder": "assets/contracts/sova-family",
      "files": ["01_общий_договор.pdf", "02_договор_Катя_реквизиты.pdf", "03_реквизиты_Елена.png"],
      "note": "общий договор семьи Сова — Елена и Катя"
    },
    "yulya-izotova": {
      "folder": "assets/contracts/yulya-izotova",
      "files": ["01_договор_стр1.jpg", "02_договор_стр2_условия.jpg", "03_договор_стр3_подпись.jpg", "04_согласие_на_ПД.jpg", "05_подпись_доп.png"]
    },
    "yulya-lushina": {
      "folder": "assets/contracts/yulya-lushina",
      "files": ["договор.pdf"]
    },
    "ekaterina-mariya-pair": {
      "byParent": {
        "Лихолева Елена Сергеевна": {
          "folder": "assets/contracts/ekaterina-mariya-pair/elena-likholeva",
          "files": ["01_договор_стр1.jpg", "02_договор_стр2_условия.jpg", "03_договор_стр3_подпись.jpg", "04_согласие_на_ПД.jpg"],
          "child": "Маша Кузнецова"
        },
        "Медведева Марина Сергеевна": {
          "folder": "assets/contracts/ekaterina-mariya-pair/marina-medvedeva",
          "files": ["01_договор_стр1.jpg", "02_договор_стр2_условия.jpg", "03_договор_стр3_подпись.jpg", "04_согласие_на_ПД.jpg"],
          "child": "Катя Медведева"
        }
      }
    },
    "ekaterina-medvedeva-solo": {
      "folder": "assets/contracts/ekaterina-mariya-pair/marina-medvedeva",
      "files": ["01_договор_стр1.jpg", "02_договор_стр2_условия.jpg", "03_договор_стр3_подпись.jpg", "04_согласие_на_ПД.jpg"]
    },
    "maria-kuznetsova-solo": {
      "folder": "assets/contracts/ekaterina-mariya-pair/elena-likholeva",
      "files": ["01_договор_стр1.jpg", "02_договор_стр2_условия.jpg", "03_договор_стр3_подпись.jpg", "04_согласие_на_ПД.jpg"]
    }
  }
};
