/* Generated snapshot — see _rebuild_cabinet_data.js (recreate via Claude/MCP). */
window.NGE_DATA = {
  "version": 2,
  "generated": "2026-05-16T16:05:00.000Z",
  "generated_by": "Claude Opus 4.7 — Notion snapshot + parent data from signed contracts",
  "note": "PIN derived deterministically from student id. Teacher password SHA-256 hashed. Parent ФИО/passport/email/phone added from scanned contracts on 2026-05-16.",
  "teacher": {
    "id": "teacher",
    "name": "Мария Витальевна Бурцева",
    "passwordHash": "94d5d02aa86a4ad402c54025da0f758d9781db2de21c22c601c1903e7a8148ce"
  },
  "payment": {
    "tinkoffQuickPay": "https://www.tinkoff.ru/rm/r_PnDqHEqsDu.EkrmOLeXmQ/MIhLS10143",
    "telegram": "https://t.me/MariaBurceva_English",
    "phone": "89165101792",
    "recipient": "Бурцева Мария Витальевна",
    "contract": "5181572792",
    "account": "40817810200014652973",
    "bik": "044525974",
    "bank": "АО \"ТБанк\"",
    "correspondentAccount": "30101810145250000974",
    "inn": "7710140679",
    "kpp": "771301001",
    "purpose": "Перевод средств по договору № 5181572792 Бурцева Мария Витальевна НДС не облагается"
  },
  "students": [
    {
      "id": "andrei-kruglov",
      "notion_id": "34d7364c-ba79-81e0-9e00-eb54d63b0dc1",
      "name": "Андрей Круглов",
      "level": "B2",
      "format": "индивидуально",
      "duration": "1.5 часа",
      "lessons_per_week": 2,
      "schedule": "вторник 14:30 / четверг 10:30 (+20 мин)",
      "goal": "разговорный английский, школа, подготовка к TOEFL/IELTS",
      "price_per_lesson": 2500,
      "monthly_package": 20000,
      "weekly_revenue": 5000,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contact_passport": "4520 965594",
      "contact_phone": "+79166988892",
      "contact_address": "Москва, ул. Ю. Парковая, 15-244",
      "pin": "1721",
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-05", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-07", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-12", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-14", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-19", "num": 5, "status": "planned", "topic": "" },
        { "date": "2026-05-21", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-26", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "sova-elena",
      "notion_id": "34d7364c-ba79-81ba-b4d6-e8b07e6ed7f7",
      "name": "Сова Елена Витальевна",
      "level": "A2",
      "format": "индивидуально",
      "schedule": "вторник 19:00",
      "goal": "взрослый ученик, медленный темп, через карточки и опоры",
      "price_per_lesson": 2000,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contact_passport": "4524 №179806 (ГУ МВД по г.Москве, 20.06.2024)",
      "contact_phone": "+79671403548",
      "contact_email": "elenavit-2005@mail.ru",
      "contact_address": "105203, Москва, ул. Первомайская, д.113, кв.29",
      "pin": "2547",
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-05", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-12", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-19", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-26", "num": 4, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "sova-ekaterina",
      "notion_id": "34d7364c-ba79-810e-ac5b-f35b5a113898",
      "name": "Сова Екатерина",
      "level": "B1",
      "format": "индивидуально",
      "schedule": "понедельник 18:00",
      "payment_status": "Оплачено",
      "parent_name": "Сова Елена Витальевна",
      "parent_passport": "4524 №179806",
      "parent_phone": "+79671403548",
      "parent_email": "elenavit-2005@mail.ru",
      "parent_address": "105203, Москва, ул. Первомайская, д.113, кв.29",
      "pin": "6924",
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-11", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-18", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-25", "num": 4, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "fedor-protasov",
      "notion_id": "34d7364c-ba79-8135-bda3-f409c1cf93a2",
      "name": "Фёдор Протасов",
      "level": "",
      "format": "индивидуально",
      "schedule": "вторник 16:00 / четверг 20:15 / пятница 20:00",
      "goal": "Spotlight 9 + страны + Past Simple irregular + there is/are/was/were",
      "level": "A2/B1",
      "lessons_in_package": 13,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 5,
      "payment_status": "Оплачено",
      "payment_note": "Мария Петровна платит еженедельно",
      "parent_name": "Протасова Мария Петровна",
      "contract_note": "бумажный договор, не онлайн",
      "pin": "7186",
      "stability_note": "Май-абонемент. 5 уроков completed (1, 5, 7, 8, 12). 14 и 15 — технические трудности, перенесены на 17 (суббота, 1.5 часа комбинированно). Сегодня (17.05) — этот комбинированный урок. Дальше 19, 21, 22, 26, 28, 29.",
      "lessons": [
        { "date": "2026-05-01", "num": 1, "status": "completed", "topic": "Туристический английский — Китай (лексика, клише)" },
        { "date": "2026-05-05", "num": 2, "status": "completed", "topic": "Туристический английский — Италия" },
        { "date": "2026-05-07", "num": 3, "status": "completed", "topic": "Грамматический юнит" },
        { "date": "2026-05-08", "num": 4, "status": "completed", "topic": "Повторение неправильных глаголов" },
        { "date": "2026-05-12", "num": 5, "status": "completed", "topic": "Туристические клише" },
        { "date": "2026-05-14", "num": 6, "status": "rescheduled", "topic": "Перенесён на 17.05 (технические трудности)" },
        { "date": "2026-05-15", "num": 7, "status": "rescheduled", "topic": "Перенесён на 17.05 (технические трудности)" },
        { "date": "2026-05-17", "num": 8, "status": "planned", "topic": "Комбинированный урок 1.5 часа (за 14 и 15.05)" },
        { "date": "2026-05-19", "num": 9, "status": "planned", "topic": "" },
        { "date": "2026-05-21", "num": 10, "status": "planned", "topic": "" },
        { "date": "2026-05-22", "num": 11, "status": "planned", "topic": "" },
        { "date": "2026-05-26", "num": 12, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 13, "status": "planned", "topic": "" },
        { "date": "2026-05-29", "num": 14, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "ivanov-ivan",
      "notion_id": "3537364c-ba79-813d-a84b-ee42fad1bd19",
      "name": "Иванов Иван",
      "level": "B1+/B2",
      "format": "индивидуально",
      "schedule": "пятница 17:30",
      "price_per_lesson": 2000,
      "monthly_package": 10000,
      "lessons_in_package": 5,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 3,
      "payment_status": "Оплачено",
      "parent_name": "Подлесных Татьяна Анатольевна",
      "parent_passport": "4524 514335 (06.11.2024)",
      "parent_phone": "+79057502111",
      "parent_email": "ryabina8@list.ru",
      "parent_address": "Москва, пос. Сосенское, п. Коммунарка, ул. Ясная, д.5, кв.33",
      "pin": "7670",
      "lessons": [
        { "date": "2026-05-01", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-08", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-15", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-22", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-29", "num": 5, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "daniella-libova",
      "notion_id": "34d7364c-ba79-81af-9ba9-f423aede5524",
      "name": "Даниэлла Либова",
      "level": "B2+",
      "format": "индивидуально",
      "schedule": "понедельник 18:00 / четверг 18:00",
      "goal": "подготовка к ЕГЭ (word formation, exam speaking)",
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 3,
      "stability_note": "Май-абонемент 8 уроков. Отыграно 3 (4, 7, 11 — completed). 14 — пропущен/перенесён (четверг не был). Дальше 18, 21, 25, 28.",
      "payment_status": "Оплачено",
      "parent_name": "Либова Юлия Игоревна",
      "contract_note": "без договора",
      "pin": "5376",
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "completed", "topic": "ЕГЭ-практика (тему уточнить)" },
        { "date": "2026-05-07", "num": 2, "status": "completed", "topic": "ЕГЭ-практика (тему уточнить)" },
        {
          "date": "2026-05-11", "num": 3, "status": "completed", "topic": "устные части ЕГЭ",
          "homework": {
            "text": "Пройти Word Building (префиксы и суффиксы) — упражнения 1 и 2. К следующему уроку.",
            "module_url": "../lingua-boost-lab/b1/word-building-prefixes-and-suffixes.html",
            "module_title": "Word Building"
          }
        },
        { "date": "2026-05-14", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-18", "num": 5, "status": "planned", "topic": "" },
        { "date": "2026-05-21", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-25", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "denis-shalmanov",
      "notion_id": "34d7364c-ba79-81a5-bdd8-ce47d7b050d7",
      "name": "Денис Шалманов",
      "level": "A1",
      "format": "индивидуально",
      "schedule": "воскресенье 10:30",
      "price_per_lesson": 2500,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contract_note": "отсканированный договор, требует визуальной сверки",
      "pin": "6347",
      "lessons_in_package": 5,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 3,
      "stability_note": "5 воскресений в мае. Оплачено 7500 ₽ = 3 урока (3, 10, 17). 2 урока (3, 10) — перевал из апреля. 24, 31 мая — к оплате отдельно. Стабильно ходит.",
      "lessons": [
        { "date": "2026-05-03", "num": 1, "status": "completed", "topic": "одежда — лексика, описания" },
        { "date": "2026-05-10", "num": 2, "status": "completed", "topic": "Past Simple / Past Continuous, stative verbs" },
        { "date": "2026-05-17", "num": 3, "status": "completed", "topic": "дома — лексика, описания" },
        { "date": "2026-05-24", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-31", "num": 5, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "anya-isaeva",
      "notion_id": "34d7364c-ba79-8199-879a-d0400012561e",
      "name": "Аня Исаева",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 17:00",
      "price_per_lesson": 2500,
      "payment_status": "Оплачено",
      "parent_name": "Исаева Наталья Вячеславовна",
      "parent_passport": "4514 567410 (УФМС России по г.Москве)",
      "parent_email": "platemir@yandex.ru",
      "parent_address": "Москва, Береговой пр-д, д.7, кв.95",
      "pin": "2512",
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-11", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-18", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-25", "num": 4, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "yulya-lushina",
      "notion_id": "34d7364c-ba79-81b5-8215-fdfe91bec709",
      "name": "Юля Лушина",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 13:00 / среда 12:00",
      "price_per_lesson": 2000,
      "payment_status": "Оплачено",
      "parent_name": "Лушин Александр Анатольевич",
      "pin": "2223",
      "lessons_in_package": 8,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-04", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-06", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-11", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-13", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-18", "num": 5, "status": "planned", "topic": "" },
        { "date": "2026-05-20", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-25", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-27", "num": 8, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "yulya-izotova",
      "notion_id": "34d7364c-ba79-81fa-8d1b-ed43ce161b3b",
      "name": "Юля Изотова",
      "level": "A1+",
      "format": "индивидуально",
      "schedule": "понедельник 16:00 / пятница 15:30",
      "goal": "Старлайт 3 / Past Simple, неправильные глаголы, лексика по темам",
      "price_per_lesson": 2000,
      "monthly_package": 18000,
      "lessons_in_package": 9,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 4,
      "payment_status": "Оплачено",
      "parent_name": "Изотова Ольга Игоревна",
      "parent_passport": "4510 764054",
      "parent_phone": "+79269754602",
      "parent_email": "meet.me.here@mail.ru",
      "pin": "2799",
      "stability_note": "Май-абонемент 9 уроков. На 17.05 отыграно 4 (1, 4, 8, 15). 11 мая — единственный пропуск. Дальше 18, 22, 25, 29.",
      "lessons": [
        { "date": "2026-05-01", "num": 1, "status": "completed", "topic": "еда — лексика" },
        { "date": "2026-05-04", "num": 2, "status": "completed", "topic": "магазины + история про Юлию (чтение, лексика)" },
        { "date": "2026-05-08", "num": 3, "status": "completed", "topic": "контейнеры/бутылки/банки + Present Simple" },
        { "date": "2026-05-11", "num": 4, "status": "missed", "topic": "" },
        { "date": "2026-05-15", "num": 5, "status": "completed", "topic": "неправильные глаголы, времена, истории" },
        { "date": "2026-05-18", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-22", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-25", "num": 8, "status": "planned", "topic": "" },
        { "date": "2026-05-29", "num": 9, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "sofia-pavlova",
      "notion_id": "34d7364c-ba79-817f-85f8-c6f87fd4d85c",
      "name": "Соня Павлова",
      "level": "B2/B2+",
      "format": "индивидуально",
      "schedule": "четверг 17:00",
      "price_per_lesson": 2000,
      "monthly_package": 8000,
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "goal": "ЕГЭ: лексика B2+, word formation, writing, speaking",
      "payment_status": "Ожидает",
      "payment_note": "мама должна половину (4000+4000 в мае)",
      "parent_name": "Анатольева Галина Алексеевна",
      "parent_passport": "45 24 № 708384 (ГУ МВД по г.Москве)",
      "parent_address": "Москва, Зельев переулок, д.3, кв.4",
      "contract_note": "подписан мамой с критическими пометками жёлтым; дата не проставлена; мама хочет править формулировки",
      "pin": "9972",
      "lessons": [
        { "date": "2026-05-07", "num": 1, "status": "planned", "topic": "ЕГЭ: повторение лексики апреля + word formation / vocabulary MCQ" },
        { "date": "2026-05-14", "num": 2, "status": "planned", "topic": "Reading B2 / B2+: тематический текст + вопросы ЕГЭ" },
        { "date": "2026-05-21", "num": 3, "status": "planned", "topic": "Writing / email: структура, ответы, собственные вопросы" },
        { "date": "2026-05-28", "num": 4, "status": "planned", "topic": "Speaking + grammar consolidation: времена, passive, modals" }
      ]
    },
    {
      "id": "ekaterina-mariya-pair",
      "notion_id": "34d7364c-ba79-81f0-ba7f-d87dcd7dfd19",
      "name": "Екатерина и Мария",
      "level": "",
      "format": "парное занятие",
      "schedule": "четверг 18:00 / воскресенье 13:35",
      "price_per_lesson": 1500,
      "monthly_package": 12000,
      "payment_status": "Ожидает",
      "payment_note": "Лихолева Елена (мама Маши) должна половину пакета",
      "parent_name": "Медведева Марина Сергеевна (Катя) / Лихолева Елена Сергеевна (Маша)",
      "kids": [
        {
          "name": "Медведева Екатерина",
          "parent": "Медведева Марина Сергеевна",
          "parent_passport": "4523 521762 (04.05.2023)",
          "parent_phone": "+79165478727",
          "parent_email": "marine_medvedeva@rambler.ru",
          "parent_address": "Москва, ул. Островитянова, д.9 кв.947"
        },
        {
          "name": "Кузнецова Мария",
          "parent": "Лихолева Елена Сергеевна",
          "parent_passport": "4519 568773 (ГУ МВД России по г.Москве)",
          "parent_email": "ivan-tenaivanova@ya.ru (уточнить)",
          "parent_address": "Москва, ул. Акад. Волгина, д.8А"
        }
      ],
      "pin": "3713",
      "lessons_in_package": 9,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "lessons": [
        { "date": "2026-05-03", "num": 1, "status": "planned", "topic": "" },
        { "date": "2026-05-07", "num": 2, "status": "planned", "topic": "" },
        { "date": "2026-05-10", "num": 3, "status": "planned", "topic": "" },
        { "date": "2026-05-14", "num": 4, "status": "planned", "topic": "" },
        { "date": "2026-05-17", "num": 5, "status": "planned", "topic": "" },
        { "date": "2026-05-21", "num": 6, "status": "planned", "topic": "" },
        { "date": "2026-05-24", "num": 7, "status": "planned", "topic": "" },
        { "date": "2026-05-28", "num": 8, "status": "planned", "topic": "" },
        { "date": "2026-05-31", "num": 9, "status": "planned", "topic": "" }
      ]
    },
    {
      "id": "katya-marakina",
      "notion_id": "34d7364c-ba79-8173-a103-f60f2bb5f124",
      "name": "Катя Маракина",
      "level": "B1",
      "format": "индивидуально",
      "schedule": "воскресенье 12:00 (90 мин) + вторник 17:00 (90 мин, наверстывание до 14.06)",
      "price_per_lesson": 2500,
      "monthly_package": 10000,
      "lessons_in_package": 4,
      "subscription_month": "2026-05",
      "lessons_used_this_month": 0,
      "stability_note": "До 14.06 — 2 урока в неделю (вс 12:00 + вт 17:00) для наверстывания 4 пропусков. С 14.06 — летний пересбор. Май: 26.04, 3.05, 10.05 cancelled (согласованные), 17.05 missed (без предупреждения).",
      "payment_status": "Оплачено",
      "parent_name": "Кедрова Татьяна Владимировна",
      "parent_passport": "45 08 445532",
      "parent_address": "Москва, Сиреневый б-р, д.44, корп.1, кв.163",
      "pin": "1265",
      "lessons": [
        { "date": "2026-04-26", "num": 1, "status": "cancelled", "topic": "Согласованный перенос (предупредили заранее)" },
        { "date": "2026-05-03", "num": 1, "status": "cancelled", "topic": "Согласованный перенос (предупредили заранее)" },
        { "date": "2026-05-10", "num": 2, "status": "cancelled", "topic": "Согласованный перенос (предупредили заранее)" },
        { "date": "2026-05-17", "num": 3, "status": "missed", "topic": "Пропуск без предупреждения" },
        { "date": "2026-05-19", "num": 4, "status": "planned", "topic": "Makeup #1 — наверстывание" },
        { "date": "2026-05-24", "num": 5, "status": "planned", "topic": "Воскресенье, регулярный слот" },
        { "date": "2026-05-26", "num": 6, "status": "planned", "topic": "Makeup #2 — наверстывание" },
        { "date": "2026-05-31", "num": 7, "status": "planned", "topic": "Воскресенье, регулярный слот" },
        { "date": "2026-06-02", "num": 8, "status": "planned", "topic": "Makeup #3 — наверстывание" },
        { "date": "2026-06-07", "num": 9, "status": "planned", "topic": "Воскресенье, регулярный слот" },
        { "date": "2026-06-09", "num": 10, "status": "planned", "topic": "Makeup #4 — наверстывание (последний)" },
        { "date": "2026-06-14", "num": 11, "status": "planned", "topic": "Воскресенье — последний урок до летнего пересбора" }
      ]
    }
  ],
  "reports": [
    {
      "id": "2026-05-anya-isaeva-parent",
      "student_id": "anya-isaeva",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Аня молодец: закончили блок по теме города, ввели Present Perfect и закрепили три формы настоящего времени — Present Simple, Present Continuous и Present Perfect. Прописали диктант; дальше — города, другие страны, спорт и travelling.",
      "content": "# Краткий вывод\n\nАня прошла первый блок занятий по понедельникам. Основной фокус был на устной базе, простых личных вопросах, there is / there are, предлогах места и городской лексике. Устная речь начала становиться увереннее: пауз меньше, фразы собираются ровнее, но грамматические конструкции нужно доводить до автоматизма.\n\n# Сегодня, 11 мая\n\nАня молодец: закончили блок по теме города, ввели Present Perfect и собрали три формы настоящего времени — Present Simple, Present Continuous и Present Perfect. Прописали диктант. Дальше переходим к полезным новым темам: города, другие страны, спорт и travelling.\n\n# Следующий фокус\n\nЗакрепление Present Simple / Present Continuous / Present Perfect через устную практику, диктанты и новые темы: города, другие страны, спорт и travelling.",
      "notion_url": "https://www.notion.so/35a7364cba7981b787b5cf8960ca9354"
    },
    {
      "id": "2026-05-denis-shalmanov-student",
      "student_id": "denis-shalmanov",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "student report",
      "recipient": "Денис Шалманов",
      "status": "ready to send",
      "title": "2026-05 — Денис Шалманов — student report",
      "short_message": "Денис, спасибо за стабильный темп в мае! 3 из 5 воскресений проведены (одежда, Past Simple / Past Continuous, дома). До конца мая — ещё 2 (24 и 31), к оплате 5 000 ₽.",
      "content": "Добрый день!\n\nОтправляю краткий отчёт по нашим занятиям за май.\n\n# Календарь занятий — май (5 занятий)\n\n- **3 мая** — Одежда: лексика, описания (завершали тему)\n- **10 мая** — Past Simple / Past Continuous, stative verbs\n- **17 мая** — Дома: лексика, описания\n- **24 мая** — *запланирован*\n- **31 мая** — *запланирован*\n\n3 из 5 проведены, 2 впереди.\n\n# По прогрессу\n\n**Мы** идём в стабильном темпе. Темы по бытовой лексике хорошо ложатся, грамматику времён (Past Simple, Past Continuous, stative verbs) разбираем основательно. Видно, что вы спокойно осваиваете новый материал и активно работаете на уроке.\n\n# Зоны роста\n\n- Вывод изученной лексики в свободную речь (пока больше в распознавании)\n- Автоматизм времён — особенно различение Past Simple vs Past Continuous в потоке\n- Расширение бытовой тематики (работа, транспорт, дорога)\n\n# Следующая задача\n\n**Вам** стоит чаще проговаривать новые слова и темы вслух между уроками — даже 10–15 минут речи о прошедшем дне в Past Simple дают сильный эффект. На уроках **мы** продолжаем тематические блоки + закрепление времён в свободной речи.\n\n# Майский абонемент\n\n5 воскресений мая (3, 10, 17, 24, 31). Стоимость занятия 2 500 ₽.\n\n- Оплачено 7 500 ₽ (3 урока: 3, 10, 17) + 2 переноса с апреля\n- К оплате за 24 и 31 мая: **5 000 ₽**\n",
      "notion_url": "https://www.notion.so/3637364cba7981a98085ef806ef7deb2"
    },
    {
      "id": "2026-05-yulya-izotova-parent",
      "student_id": "yulya-izotova",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "Изотова Ольга Игоревна",
      "status": "ready to send",
      "title": "2026-05 — Юля Изотова — parent report",
      "short_message": "Юля стабильно идёт вперёд: 4 из 9 уроков проведены (еда, магазины, контейнеры, неправильные глаголы). Формат историй работает особенно хорошо. Один пропуск 11 мая, 4 урока впереди (18, 22, 25, 29).",
      "content": "Добрый день!\n\nОтправляю краткий отчёт по занятиям **Юли** за май.\n\n# Календарь занятий — май (9 занятий)\n\n- **1 мая** — Еда: лексика\n- **4 мая** — Магазины + история про Юлию (чтение, лексика)\n- **8 мая** — Контейнеры / бутылки / банки + Present Simple\n- **11 мая** — *пропуск*\n- **15 мая** — Неправильные глаголы, времена, истории\n- **18 мая** — *запланирован*\n- **22 мая** — *запланирован*\n- **25 мая** — *запланирован*\n- **29 мая** — *запланирован*\n\n4 из 9 проведены, 1 пропуск, 4 впереди.\n\n# По прогрессу\n\nЮля стабильно идёт вперёд. Формат историй и сюжетных занятий работает особенно хорошо: через них лучше запоминается и грамматика, и тематическая лексика. На занятиях много чтения и новых слов, Юля включена.\n\n# Зоны роста\n\n- Вывод трёх времён (Present Simple, Present Continuous, Past Simple) в собственную речь — пока больше в распознавании\n- Закрепление неправильных глаголов (повторяем регулярно, нужна автоматизация)\n- Расширение тематической лексики через короткие связные истории\n\n# Следующая задача\n\nПродолжаем закреплять грамматику через истории, делаем больше устной практики. До конца мая — 4 занятия. Юле стоит каждый раз короткими историями использовать новые слова и неправильные глаголы.\n\n# Майский абонемент — 9 занятий\n\nПонедельники и пятницы. Стоимость занятия 2 000 ₽. Итого: **18 000 ₽** (оплачено).\n\nОдин пропуск 11 мая остаётся непроведённым — при возможности можем отработать или переоформить как перенос.\n",
      "notion_url": "https://www.notion.so/3637364cba798136a342cf0593982b17"
    },
    {
      "id": "2026-05-katya-sova-parent",
      "student_id": "sova-ekaterina",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Катя стабильно работает на уровне B1. В мае фокус — books / book genres, phrasal verbs и ОГЭ-формат; важно фиксировать ошибки и выводить лексику в речь.",
      "content": "# Краткий вывод\n\nКатя работает на уровне B1. Основные блоки: ОГЭ-формат, books / book genres и phrasal verbs.\n\n# Ближайший фокус\n\nBook genres → vocabulary table → questions → B1 multiple choice → matching → interview → short result check.",
      "notion_url": "https://www.notion.so/35a7364cba7981a2801af0ed869d847f"
    },
    {
      "id": "2026-05-ekaterina-medvedeva-parent",
      "student_id": "ekaterina-mariya-pair",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель (Екатерина Медведева)",
      "status": "source imported",
      "title": "Отчёт родителю Екатерины · май 2026",
      "short_message": "Катя работала ровно и стабильно: word formation, suffixes/prefixes, gerund/infinitive, used to и ОГЭ. Speaking стал собраннее, лучше держится фрейм.",
      "content": "# Краткий вывод\n\nКатя работала ровно и стабильно. Понимание тем стало лучше, speaking подрос.\n\n# Май\n\n9 занятий × 1 500 руб. = 13 500 руб.",
      "notion_url": "https://www.notion.so/35a7364cba7981bea07ddf8a902b1f13"
    },
    {
      "id": "2026-05-maria-kuznetsova-parent",
      "student_id": "ekaterina-mariya-pair",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель (Мария Кузнецова)",
      "status": "source imported",
      "title": "Отчёт родителю Марии · май 2026",
      "short_message": "Маша работает в паре с Катей. Нужна дополнительная опора на построение предложения и точечная практика: gerund/infinitive, word formation, spelling и более полные ответы.",
      "content": "# Краткий вывод\n\nМаша работает в паре с Катей и проходит те же темы. По последним работам точность временно просела: нужны опора на построение предложения и точечная практика.\n\n# Примечание\n\nОтдельной личной карточки Марии Кузнецовой не найдено, строка связана с общей карточкой пары Екатерина и Мария.",
      "notion_url": "https://www.notion.so/35a7364cba7981489de5fa224b04e372"
    },
    {
      "id": "2026-05-andrei-kruglov-toefl",
      "student_id": "andrei-kruglov",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "TOEFL diagnostic",
      "recipient": "родитель",
      "status": "source imported",
      "title": "TOEFL диагностика · 2026",
      "short_message": "Андрей показывает уверенный B2. TOEFL-style diagnostic estimate — 4.0/6.0. Сильные стороны Reading и Listening; фокус роста — Writing/Speaking accuracy.",
      "content": "# Краткий вывод\n\nАндрей показывает уверенный общий уровень B2. Диагностическая оценка по TOEFL iBT 2026 classroom scale — 4.0 из 6.0.\n\n# План\n\nReading, real-audio listening, email + academic discussion writing, structured speaking, collocations/articles/plurals.",
      "notion_url": "https://www.notion.so/35a7364cba79812492a3dcc970b5ceef"
    },
    {
      "id": "2026-05-daniella-libova-parent",
      "student_id": "daniella-libova",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "Юлия Игоревна",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Дана укрепляется: грамматика подросла, ответы стали ровнее. Сильные разделы — аудирование и чтение; зоны роста — spelling, word formation, speaking и writing по критериям ЕГЭ.",
      "content": "# Краткий вывод\n\nВ апреле Дана работала в формате подготовки к ЕГЭ: грамматика, словообразование, устная часть и диагностические задания. Подключали TOEFL-формат и Langart.\n\n# Май\n\n6 занятий к оплате после переноса 2 занятий из апреля.",
      "notion_url": "https://www.notion.so/35a7364cba7981ef858beda6387ad2f5"
    },
    {
      "id": "2026-05-yulya-lushina-parent",
      "student_id": "yulya-lushina",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Юля занимается в игровом формате. Главный прогресс — узнавание английского в понятных ситуациях, реакция на команды и повторение коротких фраз.",
      "content": "# Краткий вывод\n\nЮля занимается в игровом формате: движение, картинки, персонажи, игрушки и короткие повторяющиеся фразы.\n\n# Следующий фокус\n\nBody and face, This is my..., I have..., He/She/It has..., feelings, animals, actions.",
      "notion_url": "https://www.notion.so/35a7364cba79819c9339d3c4f4953e46"
    }
  ],
  "labModules": [
    { "level": "Pre-A1", "title": "Body & Grammar Garden", "url": "../lingua-boost-lab/pre-a1/body-and-grammar-pink.html" },
    { "level": "Pre-A1", "title": "Hello! Classroom Fun", "url": "../lingua-boost-lab/pre-a1/hello-classroom-fun.html" },
    { "level": "A1", "title": "Present Simple Routines", "url": "../lingua-boost-lab/a1/a1-01-present-simple-routines.html" },
    { "level": "A1", "title": "Present Simple Questions & Negatives", "url": "../lingua-boost-lab/a1/a1-02-present-simple-questions-negatives.html" },
    { "level": "A1", "title": "Present Simple + Adverbs of Frequency / There is/are", "url": "../lingua-boost-lab/a1/a1-03-present-simple-adverbs-frequency.html" },
    { "level": "A1", "title": "Have / Has — My Things", "url": "../lingua-boost-lab/a1/a1-04-have-has-my-things.html" },
    { "level": "A1", "title": "My / Your / His / Her", "url": "../lingua-boost-lab/a1/a1-05-my-your-his-her.html" },
    { "level": "A1", "title": "Prepositions of Place", "url": "../lingua-boost-lab/a1/a1-06-prepositions-of-place.html" },
    { "level": "A1", "title": "Instructions & Requests", "url": "../lingua-boost-lab/a1/a1-07-instructions-requests.html" },
    { "level": "A1", "title": "Final Mission (A1)", "url": "../lingua-boost-lab/a1/a1-08-final-mission.html" },
    { "level": "A1", "title": "Easter English Lesson", "url": "../lingua-boost-lab/a1/easter-english-lesson.html" },
    { "level": "A1", "title": "Past Simple Adventure", "url": "../lingua-boost-lab/a1/past-simple-adventure.html" },
    { "level": "A1", "title": "Prepositions World", "url": "../lingua-boost-lab/a1/prepositions-world.html" },
    { "level": "A1", "title": "School Words & Pronouns", "url": "../lingua-boost-lab/a1/school-words-and-pronouns.html" },
    { "level": "A2", "title": "Ancient China Explorer", "url": "../lingua-boost-lab/a2/ancient-china-explorer.html" },
    { "level": "A2", "title": "Core Trainer A2 → B1", "url": "../lingua-boost-lab/a2/core-trainer-a2-b1.html" },
    { "level": "A2", "title": "English Booster A2 → B1", "url": "../lingua-boost-lab/a2/english-booster-a2-b1.html" },
    { "level": "B1", "title": "Ancient China Cultural Studies", "url": "../lingua-boost-lab/b1/ancient-china-cultural-studies.html" },
    { "level": "B1", "title": "Grammar Arcade: Present Continuous vs Present Perfect", "url": "../lingua-boost-lab/b1/grammar-arcade-pc-pp.html" },
    { "level": "B1", "title": "Restaurant Menu Lab", "url": "../lingua-boost-lab/b1/restaurant-menu-lab.html" },
    { "level": "B1", "title": "Space Explorers", "url": "../lingua-boost-lab/b1/space-explorers-english.html" },
    { "level": "B1", "title": "Whispering Library Quest", "url": "../lingua-boost-lab/b1/whispering-library-quest.html" },
    { "level": "B1", "title": "Word Forge: Suffixes & Prefixes", "url": "../lingua-boost-lab/b1/word-building-prefixes-and-suffixes.html" },
    { "level": "B2+", "title": "Geo Quest: Articles on the Map", "url": "../lingua-boost-lab/b2-plus/articles-with-geographical-names.html" },
    { "level": "C1", "title": "Stars & Stellar Phenomena", "url": "../lingua-boost-lab/c1/stars-and-stellar-phenomena.html" }
  ]
};
