/* Generated snapshot — see _rebuild_cabinet_data.js (recreate via Claude/MCP). */
window.NGE_DATA = {
  "version": 2,
  "generated": "2026-05-16T16:05:00.000Z",
  "generated_by": "Claude Opus 4.7 — Notion snapshot + parent data from signed contracts",
  "note": "PIN derived deterministically from student id. Teacher password SHA-256 hashed. Parent ФИО/passport/email/phone added from scanned contracts on 2026-05-16.",
  "teacher": {
    "id": "teacher",
    "name": "Мария Витальевна Бурцева",
    "passwordHash": "94d5d02aa86a4ad402c54025da0f758d9781db2de21c22c601c1903e7a8148ce"
  },
  "payment": {
    "tinkoffQuickPay": "https://www.tinkoff.ru/rm/r_PnDqHEqsDu.EkrmOLeXmQ/MIhLS10143",
    "telegram": "https://t.me/MariaBurceva_English",
    "phone": "89165101792",
    "recipient": "Бурцева Мария Витальевна",
    "contract": "5181572792",
    "account": "40817810200014652973",
    "bik": "044525974",
    "bank": "АО \"ТБанк\"",
    "correspondentAccount": "30101810145250000974",
    "inn": "7710140679",
    "kpp": "771301001",
    "purpose": "Перевод средств по договору № 5181572792 Бурцева Мария Витальевна НДС не облагается"
  },
  "students": [
    {
      "id": "andrei-kruglov",
      "notion_id": "34d7364c-ba79-81e0-9e00-eb54d63b0dc1",
      "name": "Андрей Круглов",
      "level": "B2",
      "format": "индивидуально",
      "duration": "1.5 часа",
      "lessons_per_week": 2,
      "schedule": "вторник 14:30 / четверг 10:30 (+20 мин)",
      "goal": "разговорный английский, школа, подготовка к TOEFL/IELTS",
      "price_per_lesson": 2500,
      "monthly_package": 20000,
      "weekly_revenue": 5000,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contact_passport": "4520 965594",
      "contact_phone": "+79166988892",
      "contact_address": "Москва, ул. Ю. Парковая, 15-244",
      "pin": "1721"
    },
    {
      "id": "sova-elena",
      "notion_id": "34d7364c-ba79-81ba-b4d6-e8b07e6ed7f7",
      "name": "Сова Елена Витальевна",
      "level": "A2",
      "format": "индивидуально",
      "schedule": "вторник 19:00",
      "goal": "взрослый ученик, медленный темп, через карточки и опоры",
      "price_per_lesson": 2000,
      "payment_status": "Оплачено",
      "is_adult": true,
      "parent_name": "",
      "contact_passport": "4524 №179806 (ГУ МВД по г.Москве, 20.06.2024)",
      "contact_phone": "+79671403548",
      "contact_email": "elenavit-2005@mail.ru",
      "contact_address": "105203, Москва, ул. Первомайская, д.113, кв.29",
      "pin": "2547"
    },
    {
      "id": "sova-ekaterina",
      "notion_id": "34d7364c-ba79-810e-ac5b-f35b5a113898",
      "name": "Сова Екатерина",
      "level": "B1",
      "format": "индивидуально",
      "schedule": "понедельник 18:00",
      "payment_status": "",
      "parent_name": "Сова Елена Витальевна",
      "parent_passport": "4524 №179806",
      "parent_phone": "+79671403548",
      "parent_email": "elenavit-2005@mail.ru",
      "parent_address": "105203, Москва, ул. Первомайская, д.113, кв.29",
      "pin": "6924"
    },
    {
      "id": "fedor-protasov",
      "notion_id": "34d7364c-ba79-8135-bda3-f409c1cf93a2",
      "name": "Фёдор Протасов",
      "level": "",
      "format": "индивидуально",
      "schedule": "вторник 16:00 / четверг 20:15 / пятница 20:00",
      "goal": "Spotlight 9",
      "payment_status": "",
      "parent_name": "Протасова Мария Петровна",
      "contract_note": "бумажный договор, не онлайн",
      "pin": "7186"
    },
    {
      "id": "ivanov-ivan",
      "notion_id": "3537364c-ba79-813d-a84b-ee42fad1bd19",
      "name": "Иванов Иван",
      "level": "",
      "format": "индивидуально",
      "schedule": "пятница 17:30",
      "price_per_lesson": 1500,
      "monthly_package": 6000,
      "payment_status": "",
      "parent_name": "Подлесных Татьяна Анатольевна",
      "parent_passport": "4524 514335 (06.11.2024)",
      "parent_phone": "+79057502111",
      "parent_email": "ryabina8@list.ru",
      "parent_address": "Москва, пос. Сосенское, п. Коммунарка, ул. Ясная, д.5, кв.33",
      "pin": "7670"
    },
    {
      "id": "daniella-libova",
      "notion_id": "34d7364c-ba79-81af-9ba9-f423aede5524",
      "name": "Даниэлла Либова",
      "level": "",
      "format": "индивидуально",
      "schedule": "вторник 15:00 / четверг 15:00",
      "goal": "подготовка к ЕГЭ",
      "payment_status": "",
      "parent_name": "Либова Юлия Игоревна",
      "contract_note": "без договора",
      "pin": "5376"
    },
    {
      "id": "denis-shalmanov",
      "notion_id": "34d7364c-ba79-81a5-bdd8-ce47d7b050d7",
      "name": "Денис Шалманов",
      "level": "A1",
      "format": "индивидуально",
      "schedule": "воскресенье 10:30",
      "price_per_lesson": 2500,
      "payment_status": "",
      "is_adult": true,
      "parent_name": "",
      "contract_note": "отсканированный договор, требует визуальной сверки",
      "pin": "6347"
    },
    {
      "id": "anya-isaeva",
      "notion_id": "34d7364c-ba79-8199-879a-d0400012561e",
      "name": "Аня Исаева",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 17:00",
      "price_per_lesson": 2500,
      "payment_status": "",
      "parent_name": "Исаева Наталья Вячеславовна",
      "parent_passport": "4514 567410 (УФМС России по г.Москве)",
      "parent_email": "platemir@yandex.ru",
      "parent_address": "Москва, Береговой пр-д, д.7, кв.95",
      "pin": "2512"
    },
    {
      "id": "yulya-lushina",
      "notion_id": "34d7364c-ba79-81b5-8215-fdfe91bec709",
      "name": "Юля Лушина",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 13:00 / среда 12:00",
      "price_per_lesson": 2000,
      "payment_status": "",
      "parent_name": "Лушин Александр Анатольевич",
      "pin": "2223"
    },
    {
      "id": "yulya-izotova",
      "notion_id": "34d7364c-ba79-81fa-8d1b-ed43ce161b3b",
      "name": "Юля Изотова",
      "level": "",
      "format": "индивидуально",
      "schedule": "понедельник 16:00 / пятница 15:30",
      "goal": "Старлайт 3 / Grammar or reading",
      "price_per_lesson": 2000,
      "monthly_package": 16000,
      "payment_status": "",
      "parent_name": "Изотова Ольга Игоревна",
      "parent_passport": "4510 764054",
      "parent_phone": "+79269754602",
      "parent_email": "meet.me.here@mail.ru",
      "pin": "2799"
    },
    {
      "id": "sofia-pavlova",
      "notion_id": "34d7364c-ba79-817f-85f8-c6f87fd4d85c",
      "name": "Соня Павлова",
      "level": "",
      "format": "индивидуально",
      "schedule": "четверг 17:00",
      "payment_status": "",
      "parent_name": "Анатольева Галина Алексеевна",
      "parent_passport": "45 24 № 708384 (ГУ МВД по г.Москве)",
      "parent_address": "Москва, Зельев переулок, д.3, кв.4",
      "contract_note": "подписан мамой с критическими пометками жёлтым; дата не проставлена; мама хочет править формулировки",
      "pin": "9972"
    },
    {
      "id": "ekaterina-mariya-pair",
      "notion_id": "34d7364c-ba79-81f0-ba7f-d87dcd7dfd19",
      "name": "Екатерина и Мария",
      "level": "",
      "format": "парное занятие",
      "schedule": "четверг 18:00 / воскресенье 13:35",
      "price_per_lesson": 1500,
      "monthly_package": 12000,
      "payment_status": "",
      "parent_name": "Медведева Марина Сергеевна (Катя) / Лихолева Елена Сергеевна (Маша)",
      "kids": [
        {
          "name": "Медведева Екатерина",
          "parent": "Медведева Марина Сергеевна",
          "parent_passport": "4523 521762 (04.05.2023)",
          "parent_phone": "+79165478727",
          "parent_email": "marine_medvedeva@rambler.ru",
          "parent_address": "Москва, ул. Островитянова, д.9 кв.947"
        },
        {
          "name": "Кузнецова Мария",
          "parent": "Лихолева Елена Сергеевна",
          "parent_passport": "4519 568773 (ГУ МВД России по г.Москве)",
          "parent_email": "ivan-tenaivanova@ya.ru (уточнить)",
          "parent_address": "Москва, ул. Акад. Волгина, д.8А"
        }
      ],
      "pin": "3713"
    },
    {
      "id": "katya-marakina",
      "notion_id": "34d7364c-ba79-8173-a103-f60f2bb5f124",
      "name": "Катя Маракина",
      "level": "",
      "format": "индивидуально",
      "schedule": "воскресенье 12:00 (2 часа)",
      "price_per_lesson": 2500,
      "monthly_package": 10000,
      "payment_status": "",
      "parent_name": "Кедрова Татьяна Владимировна",
      "parent_passport": "45 08 445532",
      "parent_address": "Москва, Сиреневый б-р, д.44, корп.1, кв.163",
      "pin": "1265"
    }
  ],
  "reports": [
    {
      "id": "2026-05-anya-isaeva-parent",
      "student_id": "anya-isaeva",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Аня молодец: закончили блок по теме города, ввели Present Perfect и закрепили три формы настоящего времени — Present Simple, Present Continuous и Present Perfect. Прописали диктант; дальше — города, другие страны, спорт и travelling.",
      "content": "# Краткий вывод\n\nАня прошла первый блок занятий по понедельникам. Основной фокус был на устной базе, простых личных вопросах, there is / there are, предлогах места и городской лексике. Устная речь начала становиться увереннее: пауз меньше, фразы собираются ровнее, но грамматические конструкции нужно доводить до автоматизма.\n\n# Сегодня, 11 мая\n\nАня молодец: закончили блок по теме города, ввели Present Perfect и собрали три формы настоящего времени — Present Simple, Present Continuous и Present Perfect. Прописали диктант. Дальше переходим к полезным новым темам: города, другие страны, спорт и travelling.\n\n# Следующий фокус\n\nЗакрепление Present Simple / Present Continuous / Present Perfect через устную практику, диктанты и новые темы: города, другие страны, спорт и travelling.",
      "notion_url": "https://www.notion.so/35a7364cba7981b787b5cf8960ca9354"
    },
    {
      "id": "2026-05-denis-shalmanov-parent",
      "student_id": "denis-shalmanov",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Денис работает над бытовым разговорным английским, описанием картинки и короткими диалогами. Фокус — автоматизация there is / there are / it is и простые вопросы.",
      "content": "# Краткий вывод\n\nДенис занимается как взрослый ученик с практической целью: бытовой разговорный английский, описание места / картинки, вопросы и короткие диалоги.\n\n# Ближайший фокус\n\nМагазинный диалог, описание картинки / комнаты / дома, личные бытовые вопросы, Present Simple vs Present Continuous.",
      "notion_url": "https://www.notion.so/35a7364cba798199a0a9c1146281d5f8"
    },
    {
      "id": "2026-05-katya-sova-parent",
      "student_id": "sova-ekaterina",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Катя стабильно работает на уровне B1. В мае фокус — books / book genres, phrasal verbs и ОГЭ-формат; важно фиксировать ошибки и выводить лексику в речь.",
      "content": "# Краткий вывод\n\nКатя работает на уровне B1. Основные блоки: ОГЭ-формат, books / book genres и phrasal verbs.\n\n# Ближайший фокус\n\nBook genres → vocabulary table → questions → B1 multiple choice → matching → interview → short result check.",
      "notion_url": "https://www.notion.so/35a7364cba7981a2801af0ed869d847f"
    },
    {
      "id": "2026-05-ekaterina-medvedeva-parent",
      "student_id": "ekaterina-mariya-pair",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель (Екатерина Медведева)",
      "status": "source imported",
      "title": "Отчёт родителю Екатерины · май 2026",
      "short_message": "Катя работала ровно и стабильно: word formation, suffixes/prefixes, gerund/infinitive, used to и ОГЭ. Speaking стал собраннее, лучше держится фрейм.",
      "content": "# Краткий вывод\n\nКатя работала ровно и стабильно. Понимание тем стало лучше, speaking подрос.\n\n# Май\n\n9 занятий × 1 500 руб. = 13 500 руб.",
      "notion_url": "https://www.notion.so/35a7364cba7981bea07ddf8a902b1f13"
    },
    {
      "id": "2026-05-maria-kuznetsova-parent",
      "student_id": "ekaterina-mariya-pair",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель (Мария Кузнецова)",
      "status": "source imported",
      "title": "Отчёт родителю Марии · май 2026",
      "short_message": "Маша работает в паре с Катей. Нужна дополнительная опора на построение предложения и точечная практика: gerund/infinitive, word formation, spelling и более полные ответы.",
      "content": "# Краткий вывод\n\nМаша работает в паре с Катей и проходит те же темы. По последним работам точность временно просела: нужны опора на построение предложения и точечная практика.\n\n# Примечание\n\nОтдельной личной карточки Марии Кузнецовой не найдено, строка связана с общей карточкой пары Екатерина и Мария.",
      "notion_url": "https://www.notion.so/35a7364cba7981489de5fa224b04e372"
    },
    {
      "id": "2026-05-andrei-kruglov-toefl",
      "student_id": "andrei-kruglov",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "TOEFL diagnostic",
      "recipient": "родитель",
      "status": "source imported",
      "title": "TOEFL диагностика · 2026",
      "short_message": "Андрей показывает уверенный B2. TOEFL-style diagnostic estimate — 4.0/6.0. Сильные стороны Reading и Listening; фокус роста — Writing/Speaking accuracy.",
      "content": "# Краткий вывод\n\nАндрей показывает уверенный общий уровень B2. Диагностическая оценка по TOEFL iBT 2026 classroom scale — 4.0 из 6.0.\n\n# План\n\nReading, real-audio listening, email + academic discussion writing, structured speaking, collocations/articles/plurals.",
      "notion_url": "https://www.notion.so/35a7364cba79812492a3dcc970b5ceef"
    },
    {
      "id": "2026-05-daniella-libova-parent",
      "student_id": "daniella-libova",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "Юлия Игоревна",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Дана укрепляется: грамматика подросла, ответы стали ровнее. Сильные разделы — аудирование и чтение; зоны роста — spelling, word formation, speaking и writing по критериям ЕГЭ.",
      "content": "# Краткий вывод\n\nВ апреле Дана работала в формате подготовки к ЕГЭ: грамматика, словообразование, устная часть и диагностические задания. Подключали TOEFL-формат и Langart.\n\n# Май\n\n6 занятий к оплате после переноса 2 занятий из апреля.",
      "notion_url": "https://www.notion.so/35a7364cba7981ef858beda6387ad2f5"
    },
    {
      "id": "2026-05-yulya-lushina-parent",
      "student_id": "yulya-lushina",
      "month": "2026-05",
      "month_label": "май 2026",
      "type": "parent report",
      "recipient": "родитель",
      "status": "source imported",
      "title": "Отчёт родителю · май 2026",
      "short_message": "Юля занимается в игровом формате. Главный прогресс — узнавание английского в понятных ситуациях, реакция на команды и повторение коротких фраз.",
      "content": "# Краткий вывод\n\nЮля занимается в игровом формате: движение, картинки, персонажи, игрушки и короткие повторяющиеся фразы.\n\n# Следующий фокус\n\nBody and face, This is my..., I have..., He/She/It has..., feelings, animals, actions.",
      "notion_url": "https://www.notion.so/35a7364cba79819c9339d3c4f4953e46"
    }
  ]
};
