from pathlib import Path
import json


ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "diagnostic-test.html"


def q(text, options, answer):
    return {"text": text, "options": options, "answer": answer}


levels = [
    {
        "code": "A1",
        "name": "Beginner Plus",
        "desc": "A demanding beginner diagnostic: basic meaning, word order, simple tenses, articles, pronouns, prepositions and careful listening.",
        "reading": {
            "title": "Anna's first month at an English club",
            "text": "Anna is twelve, but she does not feel like a very small learner. She lives in a quiet town with her parents and her older brother. Twice a week she goes to an English club after school. The classroom is small, and there are only six students, so everyone has to speak. Anna likes this because she wants to understand songs and short videos without translating every word.\n\nAt the club, the teacher gives the students small projects. On Monday they describe their rooms, families and favourite places. On Wednesday they read short messages and answer questions. Anna is not afraid of speaking, but writing is slower for her. She often forgets articles and the letter s in he likes or she plays. At home she keeps a vocabulary notebook. Every evening she writes five new words and one example sentence.",
            "questions": [
                q("How old is Anna?", ["She is ten.", "She is twelve.", "She is sixteen."], 1),
                q("Why does Anna like the small group?", ["Everyone has to speak.", "There is no homework.", "The lessons are shorter."], 0),
                q("What does Anna want to understand?", ["Songs and short videos.", "Long novels.", "Maths problems."], 0),
                q("What do students do on Monday?", ["Describe rooms, families and favourite places.", "Write exams.", "Watch films only."], 0),
                q("What is difficult for Anna?", ["Speaking.", "Writing.", "Listening to songs."], 1),
                q("Which grammar problem is mentioned?", ["Past perfect.", "Articles and third-person s.", "Reported speech."], 1),
                q("What does Anna write every evening?", ["Five words and one example sentence.", "A long story.", "A letter to her teacher."], 0),
                q("What is the best title for the text?", ["A difficult exam", "Anna's English routine", "A family holiday"], 1),
            ],
        },
        "listening": {
            "title": "A careful first lesson",
            "script": "Teacher: Good afternoon. Before we open the book, I want to know how you learn at home.\nStudent: I usually watch short videos, but I do not always write the new words.\nTeacher: That is useful, but today I want you to write examples, not only translations.\nStudent: Should I write full sentences?\nTeacher: Yes. For example, not just 'library', but 'I go to the library after school on Friday.'\nStudent: I understand. Can I use a small notebook?\nTeacher: Yes, and bring it every lesson. We will check five words each week.\nStudent: I like that. It is easier when the words are in my own sentences.",
            "questions": [
                q("What does the teacher want to know first?", ["How the student learns at home.", "What the student ate.", "Where the student lives."], 0),
                q("What does the student usually watch?", ["Long lectures.", "Short videos.", "News programmes."], 1),
                q("What should the student write?", ["Only translations.", "Examples, not only translations.", "Nothing at home."], 1),
                q("Which example does the teacher give?", ["I go to the library after school on Friday.", "I play football every morning.", "I read a novel in summer."], 0),
                q("What should the student bring every lesson?", ["A small notebook.", "A dictionary.", "A tablet."], 0),
                q("How many words will they check each week?", ["Three.", "Five.", "Ten."], 1),
                q("Why does the student like the idea?", ["Words are easier in personal sentences.", "There is less homework.", "The teacher will not check it."], 0),
                q("What skill is the teacher mainly training?", ["Mechanical copying.", "Vocabulary in context.", "Pronunciation only."], 1),
            ],
        },
        "writing": "Extended school diagnostic task. Write 80-100 words about your English learning routine. Include: where you study, what is easy, what is difficult, and one concrete habit that can help you improve.",
        "speaking": "Record a 60-75 second answer. Introduce yourself, describe one school day, explain what is difficult in English, and give one example of how you practise at home.",
        "grammar": [
            ["Anna ___ twelve years old.", ["is", "are", "am"], 0],
            ["She ___ in a quiet town.", ["live", "lives", "living"], 1],
            ["There ___ six students in the group.", ["is", "are", "am"], 1],
            ["She writes ___ example sentence every evening.", ["a", "an", "the"], 1],
            ["My brother ___ English videos.", ["watch", "watches", "watching"], 1],
            ["I ___ afraid of speaking.", ["am not", "do not", "does not"], 0],
            ["___ your teacher check notebooks?", ["Do", "Does", "Is"], 1],
            ["We have English ___ Monday and Wednesday.", ["in", "on", "at"], 1],
            ["These are ___ new words.", ["Anna", "Annas", "Anna's"], 2],
            ["I like songs, ___ writing is difficult.", ["but", "because", "or"], 0],
            ["Choose the best question.", ["Where Anna lives?", "Where does Anna live?", "Where do Anna live?"], 1],
            ["The students ___ short messages now.", ["read", "are reading", "reads"], 1],
        ],
    },
    {
        "code": "A2",
        "name": "Elementary Strong",
        "desc": "Checks everyday comprehension with more demanding detail, past and future forms, quantifiers, comparison, modal verbs and connected speech.",
        "reading": {
            "title": "A weekend that did not go exactly as planned",
            "text": "Last weekend Pavel travelled to Saint Petersburg with his parents. They left Moscow by train on Friday evening because tickets were cheaper at night. Pavel wanted to sleep, but the carriage was noisy, and a little girl across the aisle was asking her grandmother questions about every station. When the family arrived on Saturday morning, the weather was cold but bright, so they walked along the river before visiting a museum.\n\nIn the afternoon they planned to eat in a famous cafe, but it was full. Instead, they found a small place in a side street. Pavel was disappointed at first, yet the food was excellent, and the owner told them a story about the old building. On Sunday they bought presents for friends and returned home. Pavel was tired, but he decided that unexpected changes can make a trip more interesting.",
            "questions": [
                q("Why did the family travel at night?", ["The tickets were cheaper.", "They wanted to see the sunrise.", "The museum opened at night."], 0),
                q("Why could Pavel not sleep easily?", ["The carriage was noisy.", "He lost his ticket.", "He was afraid of trains."], 0),
                q("What was the weather like on Saturday morning?", ["Cold but bright.", "Rainy and dark.", "Hot and windy."], 0),
                q("Why did they not eat in the famous cafe?", ["It was closed forever.", "It was full.", "It was too far from the station."], 1),
                q("How did Pavel feel at first about the small cafe?", ["Disappointed.", "Angry with his parents.", "Completely indifferent."], 0),
                q("What made the small cafe interesting?", ["The owner told a story.", "A singer performed.", "They met Pavel's teacher."], 0),
                q("What lesson did Pavel learn?", ["Changes can make a trip interesting.", "Trains are always uncomfortable.", "Museums are boring."], 0),
                q("Which word is closest to unexpected?", ["Planned", "Surprising", "Expensive"], 1),
            ],
        },
        "listening": {
            "title": "Changing a weekend plan",
            "script": "Mother: Pavel, the museum tickets for Saturday morning are sold out, so we need a different plan.\nPavel: Does that mean we are not going to the museum at all?\nMother: No, we can go after lunch. In the morning, we can walk near the river and take photos.\nPavel: That sounds fine. What about the cafe you wanted to visit?\nMother: I called them. There are no tables before four o'clock.\nPavel: Maybe we can find a smaller place. Sometimes those are better.\nMother: Exactly. Also, remember to take your notebook. Your teacher asked you to write ten travel words.\nPavel: I forgot about that. I will write them on the train.",
            "questions": [
                q("What problem do they have with the museum?", ["Tickets are sold out in the morning.", "It is closed all weekend.", "It moved to another city."], 0),
                q("When can they go to the museum?", ["After lunch.", "Before breakfast.", "Next month only."], 0),
                q("What will they do in the morning?", ["Walk near the river and take photos.", "Sleep in the hotel.", "Buy school books."], 0),
                q("What time are cafe tables available?", ["Before ten.", "After four.", "At noon exactly."], 1),
                q("What does Pavel suggest?", ["Find a smaller place.", "Cancel the trip.", "Eat on the train only."], 0),
                q("What must Pavel take?", ["His notebook.", "A sports bag.", "A camera charger."], 0),
                q("How many travel words should Pavel write?", ["Five.", "Ten.", "Twenty."], 1),
                q("Where will he write them?", ["On the train.", "At the museum desk.", "After returning home."], 0),
            ],
        },
        "writing": "School email diagnostic task. Write 100-120 words to a friend about a weekend plan that changed. Explain what changed, how you felt, and why the final result was useful or interesting.",
        "speaking": "Record 90 seconds. Describe a trip or school event that changed unexpectedly. Use past forms, at least one comparison, and one sentence about a future plan.",
        "grammar": [
            ["We ___ to Saint Petersburg last weekend.", ["go", "went", "gone"], 1],
            ["They ___ by train because it was cheaper.", ["travelled", "were travelling", "travels"], 0],
            ["The cafe was ___ than they expected.", ["good", "better", "best"], 1],
            ["There were not ___ tables before four.", ["some", "any", "much"], 1],
            ["Pavel has ___ travel words to write.", ["a few", "much", "many of"], 0],
            ["He ___ write them on the train.", ["is going to", "went to", "goes to"], 0],
            ["You ___ take your notebook.", ["must", "must to", "musting"], 0],
            ["The tickets ___ sold out.", ["was", "were", "did"], 1],
            ["They found a cafe ___ a side street.", ["on", "in", "at"], 1],
            ["The owner told ___ a story.", ["they", "them", "their"], 1],
            ["If the cafe is full, we ___ another place.", ["find", "will find", "found"], 1],
            ["He was tired, ___ he enjoyed the trip.", ["but", "so", "because"], 0],
            ["Have you ___ been to Saint Petersburg?", ["ever", "already", "yet"], 0],
            ["This is the place ___ we ate lunch.", ["where", "which", "who"], 0],
        ],
    },
    {
        "code": "B1",
        "name": "Intermediate Academic",
        "desc": "Tests narrative detail, inference, connected grammar, passive voice, conditionals, reported speech and early academic explanation.",
        "reading": {
            "title": "Why confidence is not the same as comfort",
            "text": "When Sofia joined an online English group, she expected the lessons to feel easier than school. She imagined that speaking from her room would be less stressful than speaking in front of classmates. The first lesson proved the opposite. Because the group was small, the teacher asked everyone to respond several times. Sofia knew many grammar rules, but she paused whenever she had to express a personal opinion.\n\nAfter a month, she noticed a pattern. Her problem was not a lack of knowledge; it was the habit of waiting until a sentence was perfect. The teacher began giving tasks with time limits: thirty seconds to prepare, one minute to speak, and then a short correction. Sofia still made mistakes, but she became more willing to try. By the end of the course, she understood that confidence grows through repeated controlled difficulty, not through avoiding uncomfortable tasks.",
            "questions": [
                q("What did Sofia expect before joining the group?", ["Online lessons would feel easier.", "The teacher would ignore her.", "There would be no speaking."], 0),
                q("Why was the first lesson difficult?", ["Everyone had to respond several times.", "The internet failed.", "The text was too long."], 0),
                q("What was Sofia's real problem?", ["Waiting for perfect sentences.", "Not knowing any grammar.", "Refusing to do homework."], 0),
                q("What kind of tasks did the teacher introduce?", ["Timed speaking tasks.", "Only translation tasks.", "Silent reading tasks."], 0),
                q("What changed by the end?", ["Sofia became more willing to try.", "She stopped making mistakes completely.", "She left the group."], 0),
                q("What does controlled difficulty mean here?", ["A challenge with structure and support.", "A task with no help.", "An exam with no time limit."], 0),
                q("Which statement is closest to the main idea?", ["Confidence develops through practice under pressure.", "Comfort is always the best learning condition.", "Grammar rules are unnecessary."], 0),
                q("What can be inferred about the teacher?", ["The teacher used pressure carefully.", "The teacher disliked mistakes.", "The teacher avoided feedback."], 0),
            ],
        },
        "listening": {
            "title": "Teacher feedback after a trial lesson",
            "script": "Teacher: Sofia, your reading is stronger than your speaking, but that is not unusual.\nStudent: I felt slow when I had to answer without writing first.\nTeacher: Yes, because you are trying to edit every sentence before you say it. That makes your speech accurate, but hesitant.\nStudent: Should I stop thinking about grammar?\nTeacher: Not exactly. You need two modes: a fluency mode, where you keep speaking, and an accuracy mode, where we correct patterns later.\nStudent: So mistakes are not the main problem?\nTeacher: Repeated mistakes matter, but silence can hide even more. Next week we will use short timed responses and then analyse three grammar patterns.\nStudent: That sounds difficult, but clear.",
            "questions": [
                q("Which skill is stronger for Sofia?", ["Reading.", "Speaking.", "Writing."], 0),
                q("Why does she speak slowly?", ["She edits every sentence before speaking.", "She does not hear the teacher.", "She has no vocabulary at all."], 0),
                q("What are the two modes?", ["Fluency and accuracy.", "Reading and drawing.", "Listening and copying."], 0),
                q("What can silence hide?", ["Problems that need diagnosis.", "Perfect grammar.", "A completed task."], 0),
                q("What will they do next week?", ["Timed responses and grammar analysis.", "Only vocabulary dictation.", "A final exam."], 0),
                q("How does the student react?", ["She thinks it is difficult but clear.", "She refuses.", "She says it is too easy."], 0),
                q("What is the teacher's attitude to mistakes?", ["Repeated mistakes matter, but they can be analysed.", "Mistakes are forbidden.", "Mistakes are never important."], 0),
                q("What kind of feedback is this?", ["Diagnostic and practical.", "Purely emotional.", "Unrelated to learning."], 0),
            ],
        },
        "writing": "Structured opinion diagnostic task. Write 130-160 words: Some students wait until they can speak perfectly; others believe they should speak even with mistakes. Which approach is better for progress? Explain with examples.",
        "speaking": "Record 2 minutes. Explain a skill you improved through uncomfortable practice. Give the situation, the difficulty, the strategy and the result.",
        "grammar": [
            ["Sofia ___ many grammar rules before she joined the group.", ["had known", "has known", "knows"], 0],
            ["She expected online lessons ___ easier.", ["to be", "being", "be"], 0],
            ["The teacher asked everyone ___ several times.", ["respond", "to respond", "responding"], 1],
            ["If she waits for perfection, she ___ fluency.", ["will lose", "lost", "would have lost"], 0],
            ["The tasks ___ by the teacher with time limits.", ["were designed", "designed", "have designing"], 0],
            ["She became more willing ___ mistakes.", ["make", "to make", "making"], 1],
            ["Although the task was stressful, she ___ it useful.", ["found", "has found", "was found"], 0],
            ["The teacher said that silence ___ problems.", ["can hide", "could hide", "will hiding"], 1],
            ["By the end of the course, she ___ more confident.", ["had become", "has become", "becomes"], 0],
            ["She used to ___ before speaking.", ["pause", "pausing", "paused"], 0],
            ["A learner ___ avoids difficulty may stop progressing.", ["who", "which", "where"], 0],
            ["The more she practised, ___ fluent she became.", ["more", "the more", "the most"], 1],
            ["Despite ___ nervous, she answered.", ["being", "be", "to be"], 0],
            ["I wish I ___ speaking earlier.", ["started", "had started", "start"], 1],
            ["Neither comfort nor speed ___ enough for progress.", ["are", "is", "were"], 1],
            ["Her answer was clear, ___ not completely accurate.", ["although", "despite", "because"], 0],
        ],
    },
    {
        "code": "B2",
        "name": "Upper-Intermediate Exam Route",
        "desc": "A hard B2 diagnostic: inference, argument, cohesive writing, complex clauses, inversion, passive structures and exam-style judgement.",
        "reading": {
            "title": "Digital attention and the illusion of productivity",
            "text": "Schools often introduce digital platforms with the promise of efficiency. Assignments can be submitted instantly, feedback can be stored, and parents can see progress without waiting for a meeting. Yet efficiency is not the same as learning. A student may move quickly through online tasks while paying only partial attention. Notifications, open tabs and the habit of checking messages can turn a thirty-minute assignment into a sequence of interruptions.\n\nThe problem is not technology itself but the absence of attention training. Students are often told to be responsible online, but they are rarely taught what responsibility looks like in practical terms. A well-designed digital task should include a goal, a time limit, a pause for checking understanding and a short reflection. Without these elements, a platform may produce the appearance of independent work while quietly weakening concentration. The most successful learners are not those who use the most tools, but those who know when to close them.",
            "questions": [
                q("What distinction does the text make?", ["Efficiency is not the same as learning.", "Parents dislike digital platforms.", "Online tasks are always useless."], 0),
                q("What can interrupt online work?", ["Notifications and open tabs.", "Books and pencils.", "Teacher feedback."], 0),
                q("What is the central problem?", ["Lack of attention training.", "Technology itself.", "Too much handwriting."], 0),
                q("What should a digital task include?", ["Goal, time limit, checking and reflection.", "Only speed and points.", "A long list of apps."], 0),
                q("What does appearance of independent work mean?", ["It may look productive without deep focus.", "It is always excellent.", "It is impossible to observe."], 0),
                q("Who are the most successful learners?", ["Those who know when to close tools.", "Those with the newest devices.", "Those who never use technology."], 0),
                q("Which tone best describes the text?", ["Balanced and critical.", "Angry and dismissive.", "Purely promotional."], 0),
                q("What can be inferred about digital platforms?", ["They need method, not blind use.", "They should be banned.", "They replace teachers completely."], 0),
            ],
        },
        "listening": {
            "title": "Interview on online learning",
            "script": "Interviewer: Many schools say digital platforms make students more independent. Do you agree?\nTeacher: Partly. A platform can support independence, but it can also disguise passive behaviour. Clicking through tasks is not the same as thinking.\nInterviewer: What should teachers do differently?\nTeacher: They should make the strategy visible. For example, tell students how long to work, what to ignore, when to stop and how to check whether they understood anything.\nInterviewer: So the tool is not enough.\nTeacher: Exactly. The tool creates access. The method creates learning. If the method is weak, the platform simply records weak habits more efficiently.\nInterviewer: That is a rather uncomfortable conclusion.\nTeacher: It is, but it is useful. Technology exposes planning. A careless lesson becomes careless faster online.",
            "questions": [
                q("What does the teacher partly agree with?", ["Platforms can support independence.", "Platforms always damage learning.", "Schools should remove all technology."], 0),
                q("What can platforms disguise?", ["Passive behaviour.", "Excellent handwriting.", "Parent meetings."], 0),
                q("What is not the same as thinking?", ["Clicking through tasks.", "Reading deeply.", "Asking questions."], 0),
                q("What should be made visible?", ["The learning strategy.", "The teacher's private notes.", "The school budget."], 0),
                q("What does the tool create?", ["Access.", "Learning by itself.", "Motivation automatically."], 0),
                q("What creates learning?", ["Method.", "Speed.", "Decoration."], 0),
                q("What does technology expose?", ["Planning.", "Personality.", "Marks only."], 0),
                q("What is the speaker's overall view?", ["Conditional and analytical.", "Naively enthusiastic.", "Completely negative."], 0),
            ],
        },
        "writing": "IELTS Task 2 / TOEFL independent hybrid. Write 180-220 words: Digital tools improve education only when students are explicitly taught how to manage attention. To what extent do you agree?",
        "speaking": "Record 2-3 minutes. Defend a position on online learning. Include one concession, one example from school practice, and one condition under which your argument might be wrong.",
        "grammar": [
            ["Had students been trained properly, they ___ fewer distractions.", ["would face", "would have faced", "will face"], 1],
            ["Not only ___ tasks faster, but they also submitted better reflections.", ["they completed", "did they complete", "they did complete"], 1],
            ["The platform ___ to support independent work.", ["is designed", "designs", "is designing itself"], 0],
            ["Students need to know when ___ tools.", ["closing", "to close", "close"], 1],
            ["The issue is not whether tools are used, ___ how they are used.", ["but", "whereas", "despite"], 0],
            ["A lesson that lacks structure is likely ___ online.", ["to fail", "failing", "fail"], 0],
            ["The more interruptions students face, ___ their attention becomes.", ["weaker", "the weaker", "the weakest"], 1],
            ["It is essential that each learner ___ a clear goal.", ["has", "have", "will have"], 1],
            ["The teacher explained how the task ___ completed.", ["should be", "should", "has being"], 0],
            ["If the method were stronger, the result ___ different.", ["will be", "would be", "would have been"], 1],
            ["The claim, ___ attractive, is incomplete.", ["although", "despite", "because"], 0],
            ["Students are rarely taught ___ responsibility looks like.", ["what", "that", "which"], 0],
            ["The task was completed, but the reflection ___ superficial.", ["remained", "remaining", "has remained to"], 0],
            ["This is the habit ___ teachers should train explicitly.", ["which", "who", "where"], 0],
            ["No sooner had the lesson started ___ messages appeared.", ["than", "then", "that"], 0],
            ["The platform records habits, ___ it does not necessarily improve them.", ["yet", "despite", "whereby"], 0],
            ["Students should be prevented ___ multitasking during the first attempt.", ["from", "to", "of"], 0],
            ["The feedback was detailed enough ___ useful.", ["being", "to be", "be"], 1],
        ],
    },
    {
        "code": "C1",
        "name": "Advanced Academic",
        "desc": "Advanced diagnostic for nuanced reading, argument structure, register, academic lexis, reduced clauses, inversion, modality and precision.",
        "reading": {
            "title": "Assessment as interpretation rather than measurement",
            "text": "Educational progress is often treated as if it must be visible, numerical and immediate. Test scores, attendance charts and completion rates are attractive because they create the impression of control. Yet the most important changes in learning may be indirect: a student begins to tolerate uncertainty, notices patterns, asks better questions or becomes less dependent on translation. These shifts are difficult to measure, but they often explain later improvement.\n\nThis does not mean that assessment is useless. On the contrary, careful assessment can make invisible progress easier to discuss. The danger appears when numbers become the aim rather than the evidence. A diagnostic test should therefore be read as a map, not a verdict. It shows where the learner is now, which strategies are available and what kind of support is likely to be productive. A strong diagnostic process also accepts asymmetry. One learner may write accurately but speak cautiously; another may understand sophisticated texts yet produce repetitive grammar.\n\nThe teacher's task is to interpret these patterns without turning them into a fixed identity. Feedback should be specific enough to guide action and humane enough to keep the learner moving. In this sense, diagnosis is not a gatekeeping ritual. It is a professional conversation about direction.",
            "questions": [
                q("What does the author criticise?", ["The obsession with immediately visible measurement.", "All forms of assessment.", "Students who ask questions."], 0),
                q("Which example of invisible progress is mentioned?", ["Tolerating uncertainty.", "Winning a prize.", "Memorising all rules."], 0),
                q("What is the danger of numbers?", ["They can become the aim rather than evidence.", "They are always inaccurate.", "They cannot be discussed."], 0),
                q("What does map, not a verdict imply?", ["Diagnostics should guide routes, not define identity.", "Maps are more beautiful than scores.", "Tests should be removed."], 0),
                q("What is asymmetry in this context?", ["Different strengths across skills.", "A mathematical concept only.", "A sign of failure."], 0),
                q("What should feedback do?", ["Guide action and keep the learner moving.", "Sound severe and final.", "Avoid concrete comments."], 0),
                q("What is the author's view of assessment?", ["Useful when interpreted carefully.", "Completely useless.", "Only useful for attendance."], 0),
                q("What genre is the text closest to?", ["Reflective academic argument.", "Personal diary.", "Advertisement."], 0),
            ],
        },
        "listening": {
            "title": "Academic discussion of diagnostic labels",
            "script": "Lecturer: The word level is convenient, but convenience can become dangerous if we forget what it hides.\nStudent: Do you mean that a B2 learner may not really be B2?\nLecturer: Not exactly. The label may be broadly accurate, but it is never a full description. Two learners can share a level and require entirely different routes.\nStudent: For example, one may speak fluently but write inaccurately?\nLecturer: Precisely. Another may read complex texts but avoid spontaneous interaction. The diagnostic question is not simply where the learner belongs, but what kind of support the pattern suggests.\nStudent: So the result is a starting point.\nLecturer: Yes, and a responsible teacher keeps the label provisional. It helps us begin the conversation; it should not end it.",
            "questions": [
                q("Why can the word level be dangerous?", ["It hides important differences.", "It is never convenient.", "It has no practical use."], 0),
                q("What does the lecturer say about labels?", ["They may be broadly accurate but incomplete.", "They are always false.", "They replace diagnosis."], 0),
                q("What example does the student give?", ["Fluent speaking but inaccurate writing.", "Perfect writing and no reading.", "No vocabulary at all."], 0),
                q("What is the diagnostic question?", ["What support the pattern suggests.", "Which label sounds better.", "How fast the test can end."], 0),
                q("What should a responsible teacher do?", ["Keep the label provisional.", "Never use labels.", "Give only a score."], 0),
                q("What does provisional mean here?", ["Open to revision.", "Completely random.", "Officially certified."], 0),
                q("What is the relationship between label and conversation?", ["The label begins it; it should not end it.", "The label replaces it.", "The conversation should avoid evidence."], 0),
                q("What is the tone?", ["Nuanced and analytical.", "Sarcastic and hostile.", "Purely narrative."], 0),
            ],
        },
        "writing": "TOEFL Integrated/IELTS academic-style task. Write 240-300 words: A diagnostic score should be treated as a route map rather than a verdict. Discuss the advantages and risks of this view, using examples from language learning.",
        "speaking": "Record 3 minutes. Explain why two learners with the same CEFR label may need different learning routes. Include examples across reading, listening, writing, speaking and grammar.",
        "grammar": [
            ["Had the assessment been interpreted narrowly, it ___ the learner's confidence.", ["might damage", "might have damaged", "will damage"], 1],
            ["The label is useful, ___ incomplete.", ["albeit", "despite", "whereas"], 0],
            ["It is vital that feedback ___ actionable.", ["is", "be", "will be"], 1],
            ["What matters most ___ the pattern behind the score.", ["is", "are", "being"], 0],
            ["The learner appears ___ stronger control in writing.", ["to have developed", "having developed", "to developing"], 0],
            ["Given the limited sample, conclusions should ___ cautiously.", ["interpret", "be interpreted", "interpreting"], 1],
            ["Not until later ___ the asymmetry.", ["we noticed", "did we notice", "we did notice"], 1],
            ["The teacher's role is less to classify ___ to interpret.", ["than", "rather", "instead"], 0],
            ["A score may obscure differences, ___ convenient it seems.", ["however", "despite", "whereas"], 0],
            ["The task, ___ designed for advanced learners, was accessible.", ["although", "despite", "because"], 0],
            ["Learners differ in the extent ___ they tolerate uncertainty.", ["to which", "where", "what"], 0],
            ["The feedback was specific enough ___ action.", ["guiding", "to guide", "guide"], 1],
            ["Far from being useless, assessment ___ discussion.", ["enables", "is enabling to", "enable"], 0],
            ["The more nuanced the feedback, ___ useful the route.", ["more", "the more", "most"], 1],
            ["No single task can account ___ the whole learner.", ["for", "about", "of"], 0],
            ["The result should not be mistaken ___ identity.", ["for", "as", "to"], 0],
            ["The student wrote accurately, ___ cautiously.", ["yet spoke", "despite spoke", "whereby speaking"], 0],
            ["If numbers become the aim, evidence ___ distorted.", ["becomes", "will have", "would have been"], 0],
            ["The process requires not only measurement ___ interpretation.", ["but also", "and also", "whereas"], 0],
            ["A learner may understand complex texts while ___ repetitive grammar.", ["producing", "produce", "to produce"], 0],
            ["The conclusion is tentative, ___ still useful.", ["yet", "despite", "whereas"], 0],
            ["Teachers should avoid ___ patterns into fixed identities.", ["turning", "to turn", "turn"], 0],
        ],
    },
    {
        "code": "C2",
        "name": "Proficiency Diagnostic",
        "desc": "A long advanced diagnostic for precision, register, rhetorical judgement, implication, stance, syntactic control and academic argument.",
        "reading": {
            "title": "Proficiency, judgement and the problem of excessive language",
            "text": "At the highest levels, language proficiency is rarely a matter of knowing more grammar in a simple quantitative sense. The learner's challenge becomes rhetorical: choosing how direct to be, deciding which implication can be left unstated, recognising when precision becomes pedantry, and when fluency begins to conceal vagueness. A speaker may produce complex sentences and still fail to sound intellectually controlled if every idea is overstated or every qualification is treated as a decorative flourish.\n\nThis is why advanced diagnostics should not merely ask whether a structure is correct. Correctness remains necessary, but it is no longer sufficient. The stronger question is whether the language is proportionate to the situation. A complaint to an institution, an academic response, a seminar intervention and a personal reflection may all require accurate grammar, yet they demand different degrees of compression, tact and explicitness. The advanced learner must therefore demonstrate not just range, but restraint.\n\nTask design can distort this judgement. A simplistic prompt may reward speed while concealing weak interpretation; an excessively academic prompt may reward familiarity with a genre rather than genuine control. A responsible C2 diagnostic uses several lenses: dense reading, layered listening, extended writing, spontaneous speaking and grammar items that test judgement as well as form. It should ask not only whether an answer is correct, but whether it is purposeful, responsive to context and stylistically mature.\n\nThe best feedback at this level sounds less like a verdict and more like an editorial conversation. It notices when complexity becomes ornament, when caution becomes evasion, and when fluency loses precision. It does not punish ambition, but it asks the learner to choose. At C2, excellence is often the capacity to use less language more exactly.",
            "questions": [
                q("What is the main claim about highest-level proficiency?", ["It depends on rhetorical judgement, not just more grammar.", "It is mainly vocabulary quantity.", "It removes the need for accuracy."], 0),
                q("When can fluency become a problem?", ["When it conceals vagueness.", "When it is too slow.", "When it uses simple words."], 0),
                q("Why is correctness insufficient?", ["Different contexts require different rhetorical choices.", "Correctness is irrelevant.", "Grammar cannot be assessed."], 0),
                q("What does proportionate language mean?", ["Language suited to situation and purpose.", "The longest possible answer.", "Language without nuance."], 0),
                q("What can a simplistic prompt conceal?", ["Weak interpretation.", "Excellent handwriting.", "Fast reading only."], 0),
                q("What risk does an excessively academic prompt create?", ["It may reward genre familiarity rather than control.", "It makes grammar impossible.", "It removes vocabulary."], 0),
                q("What should C2 grammar items test?", ["Judgement as well as form.", "Only spelling.", "Only speed."], 0),
                q("What does editorial conversation imply?", ["Precise developmental feedback.", "A final punishment.", "A casual chat without standards."], 0),
                q("What does complexity becomes ornament mean?", ["Complex language used decoratively rather than purposefully.", "All complex language is wrong.", "Ornament improves clarity."], 0),
                q("What is excellence at C2 often described as?", ["Using less language more exactly.", "Speaking as fast as possible.", "Avoiding all risk."], 0),
            ],
        },
        "listening": {
            "title": "Seminar exchange on advanced assessment",
            "script": "Speaker: I would argue that advanced assessment often over-rewards visible complexity.\nInterlocutor: Do you mean long sentences and rare vocabulary?\nSpeaker: Partly, but not only that. The problem is that complexity can imitate thought. A learner may sound impressive while avoiding a precise commitment.\nInterlocutor: So the diagnostic task should force a position?\nSpeaker: It should invite a position and then test whether the learner can qualify it without retreating into vagueness. That is a subtle difference.\nInterlocutor: How would you design such a task?\nSpeaker: I would combine a dense text, a listening extract with competing viewpoints, and a writing prompt that requires judgement rather than summary.\nInterlocutor: And grammar?\nSpeaker: Grammar should test control under pressure: concession, inversion, reduced clauses, register, and the ability to revise a sentence without flattening its meaning.\nInterlocutor: That sounds closer to editing than testing.\nSpeaker: Exactly. At this level, diagnosis is partly editorial. We are not asking whether language exists; we are asking whether it does the right work.",
            "questions": [
                q("What does advanced assessment over-reward?", ["Visible complexity.", "Silence.", "Short answers only."], 0),
                q("What can complexity imitate?", ["Thought.", "Pronunciation.", "Attendance."], 0),
                q("What is the subtle difference about position?", ["Qualifying a position without becoming vague.", "Avoiding any position.", "Changing the topic."], 0),
                q("What should the writing prompt require?", ["Judgement rather than summary.", "Only copying.", "A list of definitions."], 0),
                q("Which grammar areas are named?", ["Concession, inversion, reduced clauses and register.", "Alphabet and numbers.", "Only present simple."], 0),
                q("Why is diagnosis partly editorial?", ["It checks whether language does the right work.", "It ignores grammar.", "It is only about punctuation."], 0),
                q("What is meant by flattening meaning?", ["Losing nuance while simplifying.", "Improving precision.", "Adding evidence."], 0),
                q("What is the speaker's attitude?", ["Demanding but principled.", "Dismissive of advanced learners.", "Opposed to testing."], 0),
            ],
        },
        "writing": "IELTS Academic/TOEFL advanced hybrid. Write 350-450 words: At the highest levels, language assessment should focus less on visible complexity and more on judgement, register and rhetorical control. Discuss this claim and qualify your position.",
        "speaking": "Record 4 minutes as if responding in an academic interview. Compare two views of advanced assessment: one based on measurable accuracy, the other on rhetorical judgement. Include concession, counterexample, and a final refined position.",
        "grammar": [
            ["Visible complexity may be impressive, ___ it is not necessarily precise.", ["yet", "despite", "whereby"], 0],
            ["Were the prompt simplified too far, it ___ weak interpretation.", ["would conceal", "will conceal", "concealed"], 0],
            ["The learner sounded fluent, if ___ evasive.", ["some", "somewhat", "something"], 1],
            ["No sooner ___ a position than he qualified it.", ["he stated", "had he stated", "he had stated"], 1],
            ["The issue is not so much accuracy ___ rhetorical control.", ["as", "than", "but"], 0],
            ["Complexity should be treated as useful ___ purposeful.", ["provided it is", "despite it is", "whereby it"], 0],
            ["The feedback, ___ severe, was productive.", ["though", "despite", "whereas"], 0],
            ["A sentence may be correct without ___ appropriate.", ["being", "be", "to be"], 0],
            ["It is crucial that register ___ assessed explicitly.", ["is", "be", "will be"], 1],
            ["The task requires judgement, ___ mere summary.", ["rather than", "instead to", "whereas"], 0],
            ["Had the learner used fewer qualifiers, the argument ___ stronger.", ["might have sounded", "might sound", "will sound"], 0],
            ["The phrase was precise, ___ slightly pedantic.", ["albeit", "despite", "whereby"], 0],
            ["Not only ___ the claim, but she refined it.", ["she defended", "did she defend", "she did defend"], 1],
            ["The prompt was designed ___ evasive answers.", ["to expose", "exposing", "expose"], 0],
            ["The response lacked the restraint ___ C2 writing often requires.", ["that", "who", "where"], 0],
            ["The more advanced the learner, ___ subtle the feedback must be.", ["more", "the more", "most"], 1],
            ["The argument was not wrong; ___, it was underdeveloped.", ["rather", "despite", "whereby"], 0],
            ["A diagnostic should account ___ register and implication.", ["for", "about", "of"], 0],
            ["The sentence was revised without ___ its nuance.", ["losing", "to lose", "lose"], 0],
            ["The speaker avoided commitment, ___ weakening the answer.", ["thereby", "whereas", "despite"], 0],
            ["Useful ___ the framework is, it has limits.", ["though", "despite", "whereas"], 0],
            ["The learner's control appears ___ under timed conditions.", ["to have improved", "having improved", "to improving"], 0],
            ["The distinction is subtle, ___ pedagogically significant.", ["yet", "despite", "whereas"], 0],
            ["The answer was proportionate ___ the task.", ["to", "for", "with"], 0],
            ["If feedback becomes too general, it ___ diagnostic value.", ["loses", "would have lost", "had lost"], 0],
            ["The evaluator asked whether the register ___ the purpose.", ["served", "has served", "is serve"], 0],
        ],
    },
]


def main():
    html = HTML.read_text(encoding="utf-8")
    start = html.index("const levels = ")
    end = html.index("const levelNav", start)
    levels_js = "const levels = " + json.dumps(levels, ensure_ascii=False, indent=6) + ";\n\n    "
    HTML.write_text(html[:start] + levels_js + html[end:], encoding="utf-8")


if __name__ == "__main__":
    main()
